### ISSUE TITLE
Jenkins jobs for OpenJ9 documentation hosting solution

### ISSUE THREAD

**Issue by SueChaplain** [eclipse/openj9-docs#1]
The following Jenkins jobs are needed for when we have doc source in place at this repo and an Eclipse git repo for promoting to www.eclipse.org/openj9/docs:
 

1. Docker container: Build a docker image that contains all the build components for the MkDocs solution and store it on Docker Hub. (Mkdocs basically takes raw markdown files and builds HTML with a pre-chosen "theme"). This image can be used as the Jenkins slave container for the doc build jobs and would need updating when the build tool levels have to change (not very often I hope. We are pinning the dependencies and will be putting together a regular test process to keep reasonably current.)
2. For a pull request, a pipeline job to build the HTML from GitHub source and promote to the staging branch of the Eclipse GIT repo
3. On a merge, build the HTML from GitHub source and promote to the master branch of the Eclipse GIT repo.

For (2) and (3), we could build and post to different branches in GitHub and then sync to Eclipse ... if that is preferred? Might be easier.

**Comment by SueChaplain** [comment]
@AdamBrousseau Dan suggested I create an issue for the Jenkins work, but I put it here to avoid filling up the openj9 issues list. I see you are very busy at the moment. We are not ready to go yet .... will see what your availability is like when we get closer.

**Comment by SueChaplain** [comment]
Hi ... thanks

(1) and (2) I have a temporary Dockerfile that has exactly what we need - we're using it at the moment for testing:  https://github.com/ibmruntimes/docker-md-buildenv
The plan is to put this dockerfile into the openj9-docs repo rather than have a separate repo for it.
(3) We've got a Jenkins job that builds the image from this file and pushes it to docker.hub, so should be a simple case of transferring the job, changing the src/target, and using whatever account and privileges are needed from the Eclipse side ... @genie-openj9, if that's it? I spotted that they have an Eclipse org on docker.hub, but didn't find anything on their wiki about how to arrange using it.
(4) Yes, hope so.
(5) No other tools that I am aware of. All the build tools are in the Docker image.
(6) So far I just got the Eclipse guys to create the repo. When we have got through the CQ process and can put the source there I will raise a bugzilla to have the hook configured. Not sure I can do it beforehand.

**Comment by AdamBrousseau** [comment]
I see [docker is supported on p/z](https://docs.docker.com/install/#supported-platforms) so it shouldn't be a problem installing it on our [proxy_worker](https://ci.eclipse.org/openj9/computer/proxy_worker/) node(s) and running the builds there.

**Comment by SueChaplain** [comment]
@AdamBrousseau 

*2. For a pull request, a pipeline job to build the HTML from GitHub source and promote to the staging branch of the Eclipse GIT repo
3. On a merge, build the HTML from GitHub source and promote to the master branch of the Eclipse GIT repo.*

I've been thinking about these 2 jobs and how best to set this up. In each case we need to push the changes to Eclipse GIT (staging/master), but we want to be doing as little hands on as possible there because the environment is somewhat different from GitHub (and we had one or two oopses for the website). However, we can't just sync the master branch of the github repo like we do for the website, because the source files have to be built first. Perhaps we should make use of 2 additional branches in the git repo: staging and ghpages. 

- the PR job to test pull requests on the Eclipse staging server could build and deploy to GitHub staging, then sync to the Eclipse staging branch.
- the merge job to push the changes to the Eclipse master branch could build and deploy to GitHub ghpages, then sync to the Eclipse master branch. (Mkdocs includes a command that does a ghdeploy on a successful build, so this would be easy to implement). 

Any alternative thoughts?

**Comment by SueChaplain** [comment]
Further ramblings on possibilities - this is the latest thinking:

This is the Eclipse GIT repo:  http://git.eclipse.org/c/www.eclipse.org/openj9/docs.git/

As with the existing OpenJ9 website the built HTML need pushing: 

- pushing to the master branch of the Eclipse GIT repo will publish content to http://www.eclipse.org/openj9/docs 
- pushing to the staging branch of the Eclipse GIT repo will allow us to test content at http://staging.eclipse.org/openj9/docs

Our source files are sitting on https://github.com/eclipse/openj9-docs

The source files have to be built inside the docker container, where we load up the MkDocs tooling.
When built, the HTML should be inside a /site directory in the container and this needs to end up in the Eclipse GIT root directory (staging or master branch depending on job).

How to get this there:

We could either

- push it directly to Eclipse GIT from the container? Not sure how you do this but maybe you can map a directory in the JIPP workspace.

or

- push it to a separate branch of the https://github.com/eclipse/openj9-docs repo and then sync that to Eclipse GIT (but not a ghpages branch as we won't want a duplicate site that could confuse users)

**Comment by AdamBrousseau** [comment]
Eclipse bug to add Jenkins hook to repo
https://bugs.eclipse.org/bugs/show_bug.cgi?id=534008
