### ISSUE TITLE
Guarded storage support for Linux on IBM Z

### ISSUE THREAD

**Issue by SueChaplain** [eclipse/openj9-docs#11]
Update -Xgc:concurrentScavenge to include support statement for Linux on IBM Z.
Testing complete for RHEL7.5

**Comment by fjeremic** [comment]
We should also make notes about Ubuntu 18.04 which is slated to be released in 2 days.

**Comment by SueChaplain** [comment]
Agreed. I believe testing is still in progress, but will plan to add Ubuntu 18.04 as soon as that is complete.

**Comment by dmitripivkine** [comment]
We might have an issue for zLinux. I suspected that there is a missed check for Guarded Storage support in Port Library fir zLinux. If OS does not support GS it might lead to a crash
I have open eclipse/omr#2500 to double check this
