### ISSUE TITLE
Enable bootstrap class sharing by default jdk11

### ISSUE THREAD

**Issue by hangshao0** [eclipse/openj9-docs#110]
**Issue or pull request number:**
*https://github.com/eclipse/openj9/pull/2449, https://github.com/eclipse/openj9/issues/1646*

**Overview:**
*Previously the shared classes feature will be enabled only when use specify -Xshareclasses in the CML, after this change, the share classes feature will be enabled by default. However, only bootstrap classes will be shared by default.*

**Applies to the following JDK versions:**
*Java 11 and up*

**Applies to the following platforms:**
*All platforms except OSX*

**For new command line options:**
N.A.

1. The default bootstrap class sharing is not enabled when running in container.
2. User can use option -Xshareclasses:none to disable the default bootstrap class sharing
3. The default shared cache directory is user's home directory on Unix, CSIDL_LOCAL_APPDATA (C:\Documents and Settings\username\Local Settings\Application Data) on windows, username will be used as the default cache name. 
4. The default cache size is 300MB with a softmax size of 64MB on 64-bit platforms and 16MB on non-64-bit platforms
5. The default shared cache is shared with other JVMs using -Xshareclasses with default cache name and default cache directory.
6. User can use -Xshareclasses utility sub-options to list, destroy, adjust the softmx or print the statistics of the default shared cache.
7. User can use other shared cache related options like -XX:SharedCacheHardLimit= -Xscmx -Xscminaot -Xscmaxaot -Xscminjitdata -Xscmaxjitdata -Xscdmx to control the default shared cache.
8. Trace point j9shr.2271 will be activated if the default shared cache failed to be started up. User can enable this trace point if they want to determine if the default shared cache is started up.
9. The default bootstrap class sharing is equivalent to -Xshareclasses:bootClassesOnly,silent. User can use -Xshareclasses:bootClassesOnly,verbose to debug on the default shared cache. 
10. The default shared cache won't be created if the user's home directory is on NFS (or an error occurs when getting the home directory), user can use -Xshareclasses:bootClassesOnly,cacheDir=dir to specify the cache directory.
11. If there are multiple JDK installations (of the same Java version) under the same user, the JVM always checks if the exiting default shared cache under home directory is from the same JDK. If not, it will delete the exiting default shared cache and create a new one. In this case, it is better to use -Xshareclasses:cacheDir=dir to specify different cache directory for each JDK.

**Comment by pshipton** [comment]
Re point 8 the equivalent should include nonFatal.
I think the suggestion should be to remove silent or add verbose to see information about the shared cache startup.

**Comment by hangshao0** [comment]
> Re point 8 the equivalent should include nonFatal.

BootClassesOnly will automatically turn on nonfatal. Added "verbose" to the suggestion.

**Comment by doveye** [comment]
Some questions:

> 2.	User can use option -Xshareclasses:none to disable the default bootstrap class sharing

Presumably, if the user wants app as well as bootstrap class sharing, they must specify the -Xshareclass option? And if they want app class sharing but not bootstrap class sharing (would they ever want to do this?), they can use -Xshareclasses:noBootclasspath? (It's a shame the bootClassesOnly option isn't more consistent in naming with the noBootclasspath option!)

> 3.	The default shared cache directory is user's home directory on Unix, CSIDL_LOCAL_APPDATA (C:\Documents and Settings\username\Local Settings\Application Data) on windows, username will be used as the default cache name.

Is the name really just the username, or is it "sharedcc_%u" (where %u is the username) -  this is the currently documented default for the "name" sub-option. And is the Windows dir really "C:\Documents and Settings\username\Local Settings\Application Data" - the docs currently list it as "C:\Documents and Settings\username\Local Settings\Application Data\javasharedresources"?

> 4.	The default cache size is 300MB with a softmax size of 64MB on 64-bit platforms and 16MB on non-64-bit platforms

Currently, the docs do not mention a difference in size between 64-bit/non-64-bit platforms, so is this a change (and if so, is it for OpenJDK 11 only)? The docs also mention a couple of exceptions to cache size and softmax size (see just under "Syntax" in https://www.eclipse.org/openj9/docs/xshareclasses/) - do these exceptions apply to the new default cache?

**Comment by hangshao0** [comment]
> Presumably, if the user wants app as well as bootstrap class sharing, they must specify the -Xshareclass option? 

Yes.

> And if they want app class sharing but not bootstrap class sharing (would they ever want to do this?), they can use -Xshareclasses:noBootclasspath?

Yes. (Not sure why they would want to do this)

> Is the name really just the username, or is it "sharedcc_%u" (where %u is the username) - this is the currently documented default for the "name" sub-option.

It is sharedcc_%u

> Currently, the docs do not mention a difference in size between 64-bit/non-64-bit platforms, so is this a change (and if so, is it for OpenJDK 11 only)? The docs also mention a couple of exceptions to cache size and softmax size (see just under "Syntax" in https://www.eclipse.org/openj9/docs/xshareclasses/) - do these exceptions apply to the new default cache?

The size change was done a few weeks ago. It is done on all JDK levels. (See https://github.com/eclipse/openj9-docs/issues/80 for Java 8 and https://github.com/eclipse/openj9-docs/issues/46 for Java 9 and up). Those exceptions also apply to the new default cache.

**Comment by doveye** [comment]
Thanks Hang. I think maybe it wasn't clear that the size change was only for 64-bit platforms. I've pasted a draft fix for that below, and a suggested new section for Enabling shared classes, which will go into https://www.eclipse.org/openj9/docs/shrc/ eventually. Can you please have a look and left me know if anything needs correcting, thanks. I won't make the update for the bootstrap class sharing by default, because apparently the code is not going in yet, but I can at least get a doc change ready for when it does.

**Size fix**  (this will be an update to https://www.eclipse.org/openj9/docs/xshareclasses/#syntax)

![xshareclasses_size_correction](https://user-images.githubusercontent.com/14108229/47142723-7943bd80-d2bb-11e8-9303-f89d6c88a6de.jpg)

**Suggested draft for default class sharing update:**

![shrc_draft](https://user-images.githubusercontent.com/14108229/47142724-7943bd80-d2bb-11e8-9ace-da475650cbe1.jpg)

**Comment by hangshao0** [comment]
> for example you can print statistics for it, change its size, or delete it.

The shared cache size cannot be changed. The soft maximum limit size, max/min AOT data space size and max/min JIT data space size can be changed. 

The rest looks good.

**Comment by hangshao0** [comment]
There are still some problems on OSX, so class sharing is not enabled by default on OSX. I have update the platforms from "All platforms" to "All platforms except OSX" in the description.

**Comment by doveye** [comment]
The doc updates are now live, including the Mac update and https://github.com/eclipse/openj9-docs/issues/110#issuecomment-431040872, so I'm closing this item. I'm aware another one was opened recently to port these changes back to Java 8, I'll address those separately.
