### ISSUE TITLE
Enable options for idle tuning when running in container

### ISSUE THREAD

**Issue by ashu-mehra** [eclipse/openj9-docs#112]
**Issue or pull request number:**
https://github.com/eclipse/openj9/issues/3226

**Overview:**
Enables `-XX:+IdleTuningGcOnIdle` and `-XX:+IdleTuningCompactOnIdle` when OpenJ9 is running in a container.
Doc pages https://github.com/eclipse/openj9-docs/blob/master/docs/xxidletuninggconidle.md and https://github.com/eclipse/openj9-docs/blob/master/docs/xxidletuningcompactonidle.md need to be updated to include this change in default behavior when running in container.

**Applies to the following JDK versions:**
All JDK versions

**Applies to the following platforms:**
Linux X|P|Z

**For new command line options:**
N.A.

**Comment by SueChaplain** [comment]
@ashu-mehra - I have a query.

In https://www.eclipse.org/openj9/docs/xxidletuningminidlewaittime/, we state that:

>The value used for <secs> specifies the minimum length of time in seconds that the VM is idle before the state is set to idle. Setting the value to 0 disables this feature, which causes the following idle tuning options to have no effect:

>-XX:+IdleTuningCompactOnIdle
>-XX:+IdleTuningGcOnIdle
>-XX:IdleTuningMinFreeHeapOnIdle

We also state that the default value is `0`.

I'm assuming that this topic needs updating too? What do we need to say please?

**Comment by ashu-mehra** [comment]
Yes, this is confusing. 
Actually the default value of `-XX:IdleTuningMinIdleWaitTime` is set as follows:
If either of `-XX:+IdleTuningGcOnIdle` or `-XX:+IdleTuningCompactOnIdle` is specified, then the default value is 180 secs, else, it is 0.
If the user explicitly sets the value to 0, then `-XX:+IdleTuningGcOnIdle` or `-XX:+IdleTuningCompactOnIdle` won't have any effect.

Does that help?
