### ISSUE TITLE
Allow native crypto properties values YES/NO and TRUE/FALSE

### ISSUE THREAD

**Issue by enasser** [eclipse/openj9-docs#124]
Please document the following changes to native crypto properties jdk.nativeCrypto, jdk.nativeDigest, jdk.nativeCBC and jdk.nativeGCM.

   - Allow the value of native crypto properties as YES/NO in addition
     to TRUE/FALSE as it makes more sense for end user to specify
     jdk.nativeCrypto=NO insted of jdk.nativeCrypto=FALSE.
   - Made the property value case insensitive so that user can
     specify 'YES' or 'Yes' or 'yes'.
   - Allow user to specify enable all native crypto and disable
     specific crypto
The corresponding Pull Request is https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/151

**Comment by SueChaplain** [comment]
This change did not go in. Values remain as true|false. Closing this issue.
