### ISSUE TITLE
"Markdown" backticks visible on whats new page

### ISSUE THREAD

**Issue by sxa555** [eclipse/openj9-docs#125]
**Page containing the error:**

http://www.eclipse.org/openj9/oj9_whatsnew.html

**Describe the error and the update needed:**

Seems to have all the options listed in markdown format e.g. a literal backtick on the page around the option. I presume that was unintentional and that it was intended to be displayed in a monospaced font.

**Comment by SueChaplain** [comment]
Moved to website issues list: https://github.com/eclipse/openj9-website/issues/137
