### ISSUE TITLE
-Xgc:concurrentScavenge only supported on x86 Linux in 0.11

### ISSUE THREAD

**Issue by andrewcraik** [eclipse/openj9-docs#126]
**Page containing the error:**
0.11 release notes

**Describe the error and the update needed:**
The release note says we support -Xgc:concurrentScavenge on x Linux and Windows when running with compressed references. Only Linux support ended up enabled in the release and so the docs need to remove reference to Windows support for now. We hope to address this in a future release - possibly 0.12.

**Comment by pshipton** [comment]
@doveye we should fix this quickly please before too many people try to use the feature on Windows and find its not working.

**Comment by doveye** [comment]
This info is not just in the release notes, it's also on the website (https://www.eclipse.org/openj9/oj9_whatsnew.html)  and in multiple places in the user docs (https://www.eclipse.org/openj9/docs/version0.11/, https://www.eclipse.org/openj9/docs/xgc/, and https://www.eclipse.org/openj9/docs/gc/). I have updated all three areas.

**Comment by pshipton** [comment]
I've merged the first two and requested a change in https://github.com/eclipse/openj9-docs/pull/127
