### ISSUE TITLE
Deprecate IBM_JAVA_OPTIONS and replace with OPENJ9_JAVA_OPTIONS 

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9-docs#131]
**Issue or pull request number:**
eclipse/openj9#3478

**Overview:**
The IBM IBM_JAVA_OPTIONS option should be deprecated and replaced by the OpenJ9 OPENJ9_JAVA_OPTIONS  option. The IBM SDK uses the same source and should prefer the OpenJ9-specific options

**Applies to the following JDK versions:**
All

**Applies to the following platforms:**
All

**Comment by pdbain-ibm** [comment]
Should we deprecate JAVA_TOOL_OPTIONS at the same time? We will still support it for compatibility, but OPENJ9_JAVA_OPTIONS should be the preferred variable.

**Comment by pshipton** [comment]
As I recall, JAVA_TOOL_OPTIONS is part of the spec, unless it has been removed from Java 11.

**Comment by DanHeidinga** [comment]
FYI @llxia Do any of the test scripts depend on or use IBM_JAVA_OPTIONS?  It's being replaced by an OPENJ9_JAVA_OPTIONS env var

**Comment by llxia** [comment]
From a quick look, 
- https://github.com/eclipse/openj9/blob/master/test/functional/Java8andUp/src/org/openj9/test/vmArguments/VmArgumentTests.java needs to be updated.
- https://github.com/eclipse/openj9/blob/master/test/TestConfig/resources/modes.xml will not break, but also should be updated.

Issue is created in openj9: [Update tests to use OPENJ9_JAVA_OPTIONS](https://github.com/eclipse/openj9/issues/3525)

**Comment by pdbain-ibm** [comment]
@llxia 

Thank you for your review.

VmArgumentTests was updated: https://github.com/eclipse/openj9/pull/3495/files#diff-7f1510116e93ef7b021414c1fa329409 in the same commit as the VM changes. It tests OPENJ9_JAVA_OPTIONS alone and in conjunction with other environment variables.  If there are other tests you would like, please update #3525.

I will update the modes file to use OPENJ9_JAVA_OPTIONS.

**Comment by pdbain-ibm** [comment]
We will continue to support `IBM_JAVA_OPTIONS` for the benefit of legacy applications.  We should continue to test it.

**Comment by DanHeidinga** [comment]
Sorry, I disagree.  The testing here at the OpenJ9 project should use the `OPENJ9_JAVA_OPTIONS` env var, not the IBM version.

The IBM env var is deprecated and will be removed from OpenJ9 in the future

**Comment by pdbain-ibm** [comment]
@DanHeidinga I should clarify: most tests will switch to using the new option (work on that is in progress...). However, the VmArgumentTests will continue to exercise the legacy option, though it should be the only test to use IBM_JAVA_OPTIONS.
