### ISSUE TITLE
Document JVMTI GetOSThreadID() extension

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9-docs#132]
**Subject:**
The JVMTI extensions are not yet documented, but when they are, the GetOSThreadID() extension is missing from the list at https://www.ibm.com/support/knowledgecenter/SSYKE2_8.0.0/com.ibm.java.vm.80.doc/docs/jvmti_extensions_ref.html

**Suggestion:**
This extension returns the OS thread id in the threadid_ptr parameter, that corresponds to the jthread parameter.

jvmtiError GetOSThreadID(jvmtiEnv* jvmti_env, jthread thread, jlong * threadid_ptr);

**Comment by pmhayward** [comment]
@pshipton - Hi, I'm just in process of moving all JVMTI docs to OpenJ9 and need to add this missing extension.
Putting it into the same format as all the others, I so far have the following. Does this need any more explanation? In particular, please confirm that I've guessed the extension IDs correctly and got the description of the parameters right. What other 'Returns' do I need to include?

---

## `GetOSThreadID`

You can **get the OS thread ID** by using the `GetOSThreadID()` API:

    jvmtiError GetOSThreadID(jvmtiEnv* jvmti_env, jthread thread, jlong * threadid_ptr);

The `QueryVmDump()` API has the JVMTI Extension Function identifier `com.ibm.GetOSThreadID`. The identifier is declared as macro `COM_IBM_GET_OS_THREAD_ID` in the `ibmjvmti.h` file.

**Parameters**

- `jvmti_env`: A pointer to the JVMTI environment.
- `thread`: The thread for which the ID is required.
- `threadid_ptr`: A pointer to a variable, used to return the thread ID that corresponds to the thread specified by the thread parameter.

**Returns**

`JVMTI_ERROR_NONE`: Success  
`???`

**Comment by pshipton** [comment]
Looks good. Here are the other returns.
    JVMTI_ERROR_NULL_POINTER: The threadid_ptr parameter is null.
    JVMTI_ERROR_INVALID_ENVIRONMENT: The jvmti_env parameter is invalid.
    JVMTI_ERROR_INVALID_THREAD: The thread is not valid (should never happen).
    JVMTI_ERROR_THREAD_NOT_ALIVE: The JVM state of the thread is not started or has died.
    JVMTI_ERROR_UNATTACHED_THREAD: The current thread is not attached to the JVM.
    JVMTI_ERROR_WRONG_PHASE: The extension has been called outside the JVMTI start or live phase.
