### ISSUE TITLE
Document Software-based Pauseless GC support on Power

### ISSUE THREAD

**Issue by gita-omr** [eclipse/openj9-docs#134]
https://github.com/eclipse/openj9/issues/3421

**Overview:**
I suspect the description will be very similar to the one on Intel in Z, which in turn will be just  a small delta to whatever we already say about HW based pauseless GC on Z.

**Applies to the following JDK versions:**
8 and later

**Applies to the following platforms:**
*E.g. All platforms / AIX / Linux X|P|Z / Windows / z/OS*

**For new command line options:**

- Option name and syntax: *e.g. -XX[+|-]NewOptionName*
- If values are set:  
	- Units for setting: *e.g. %, MB*
	- Range: *e.g. 0-100*
	- Default value: *e.g. 50*
- Purpose:
- Restrictions:

**Comment by SueChaplain** [comment]
@gita-omr 

Existing doc on ConcurrentScavenge is in the following topics:

- https://www.eclipse.org/openj9/docs/xgc/#concurrentscavenge
- https://www.eclipse.org/openj9/docs/gc/

It might be useful if you could take a look at these and suggest what might need updating. Your overview doesn't give us a lot to go on. Thanks!

**Comment by gita-omr** [comment]
@SueChaplain 

Thanks for the links. It makes it easier to comment.

First link: please consult @fjeremic re all the Z related info. I don't know if software-based Pauseless GC will completely replace HW based or not.

Please also consult @andrewcraik re X.

For P, the -Xgc:concurrentScavenge option will enable pauseless GC on all supported Power platforms.

Second link:
Again, I am not sure if all references to HW-based  support on Z need to be removed or not. 
For software based support, we need to replace "The GS Facility provides hardware-based support to detect when potentially stale references to objects are accessed by an application" with 
"VM and JIT check memory accesses in order to detect when potentially stale references to objects are accessed by an application"

**Comment by gita-omr** [comment]
@jimmy please review the docs as well.

**Comment by gita-omr** [comment]
In https://www.eclipse.org/openj9/docs/gc/:

Please replace

**Software-based support: (Linux on x86-64 only)**

with 

**Software-based support: (Linux on x86-64, Linux LE on Power, AIX on Power)**

**Comment by gita-omr** [comment]
In https://www.eclipse.org/openj9/docs/xgc/#concurrentscavenge 

please replace
**(64-bit: Windows, Linux on x86, Linux on IBM Z®, or z/OS® only)**

with
**(64-bit: Windows, Linux on x86, Linux on IBM Z®, z/OS®, Linux LE on Power, or AIX only)**

Basically, we need to add Linux LE on Power and AIX.

**Comment by gita-omr** [comment]
This is all the corrections I found so far.
