### ISSUE TITLE
jdk8 extra shared libraries removed

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9-docs#146]
https://github.com/ibmruntimes/openj9-openjdk-jdk8/issues/17
https://github.com/eclipse/openj9/issues/805

Once https://github.com/ibmruntimes/openj9-openjdk-jdk8/issues/17 is resolved for jdk8, it can be removed from the release notes for 0.12.0. jdk11 was fixed in an earlier release.

**Comment by SueChaplain** [comment]
Updated WIP release notes ahead of Dec milestone build: https://github.com/eclipse/openj9/pull/4076
