### ISSUE TITLE
Broken link on README.md

### ISSUE THREAD

**Issue by ksurendra** [eclipse/openj9-docs#15]
The link to **Eclipse OpenJ9 user documentation** is broken on README.md (https://github.com/eclipse/openj9-docs/blob/master/README.md)

**Comment by SueChaplain** [comment]
Hi @ksurendra. The link is not yet live .... blocked by issue #1, which @AdamBrousseau is working on. As soon as we have the Jenkins jobs working, the site will be published at the URL in the readme.

**Comment by SueChaplain** [comment]
Site now available. Closing this issue.
