### ISSUE TITLE
Large heap support for concurrent scavenge on x86

### ISSUE THREAD

**Issue by 0dvictor** [eclipse/openj9-docs#150]
**Issue or pull request number:**

eclipse/openj9#3338

**Overview:**

The above issue is tracking a series of changes being made to OpenJ9 to expand the support for pause-less garbage collector on the x86 platform: it no-longer requires compressedrefs and hence supports any available heap size.

**Applies to the following JDK versions:**

8 and later

**Applies to the following platforms:**

64-bit Linux X

**Remarks**

There is no option change. The restriction below for `-Xgc:concurrentScavenge` no-longer holds:
> Compressed references must be used. See -Xcompressedrefs.
(Compressed references are enabled by default when the maximum heap size (-Xmx) ≤ 57 GB. The concurrent scavenge option is ignored if the maximum heap size is > 57 GB.)

**Comment by SueChaplain** [comment]
@0dvictor - I think there has been some confusion with this item. Can you please confirm whether the compressed ref restriction still applies to z/OS and Linux on Z? The limitation has currently been removed from the docs completely.

**Comment by 0dvictor** [comment]
This Issue is for 64-bit Linux on X, and hence does not have any implications on status to z/OS or Linux on Z.
@fjeremic do you know if compressed ref restriction applies to z/OS and Linux on Z?

**Comment by fjeremic** [comment]
> This Issue is for 64-bit Linux on X, and hence does not have any implications on status to z/OS or Linux on Z.
> @fjeremic do you know if compressed ref restriction applies to z/OS and Linux on Z?

It does not. Concurrent scavenge (when available) on z/OS and Linux on Z will work for both compressedrefs and non-compressedrefs.

**Comment by pshipton** [comment]
I believe @fjeremic means software based concurrent scavenge #3276

**Comment by fjeremic** [comment]
> I believe @fjeremic means software based concurrent scavenge [eclipse/openj9#3276](https://github.com/eclipse/openj9/issues/3276)

Not quite,

> Concurrent scavenge (when available)

currently this is only true on z14 when we have the correct OS support and it's hardware accelerated. We do not have software CS yet, until #3276 is resolved. When CS is available (right hardware + OS levels) it will work on both compressedrefs and non-compressedrefs.

**Comment by SueChaplain** [comment]
So, just to be clear for @pmhayward, the compressedrefs restriction needs to go back in for Linux on Z and z/OS, somewhere under here:

>Note: Linux on Z and z/OS

>This option is supported on IBM z14™ hardware running the following software:

>Operating systems:

>- z/OS V2R3
>- z/OS V2R2 and APAR OA51643.
>- RHEL 7.5 (minimum kernel level 4.14)
>- Ubuntu 18.04 (minimum kernel level 4.15)

>Hypervisors:

>- IBM z/VM 6.4 with APAR VM65987
>- KVM solutions with QEMU 2.10 or later and minimum host kernel level 4.12 (for example, RHEL 7.5 with kernel level 4.14)

>If these requirements are not met, the option is ignored.

**Comment by SueChaplain** [comment]
>When CS is available (right hardware + OS levels) it will work on both compressedrefs and non-compressedrefs.

I read this statement as relating to SW-based CS, which we don't have a docs issue for yet. If that feature doesn't make 0.12.0, I'm assuming that my earlier comment is accurate? i.e. for CS with HW acceleration, it is supported only with compressedrefs.

**Comment by fjeremic** [comment]
> If that feature doesn't make 0.12.0, I'm assuming that my earlier comment is accurate? i.e. for CS with HW acceleration, it is supported only with compressedrefs.

Let's be explicit here. On z/Architecture the following is currently true:

|                    | Software CS                         | Hardware CS |
|--------------------|-------------------------------------|-------------|
| Compressedrefs     | unsupported (until #3276 is complete) | supported   |
| Non-compressedrefs | unsupported (until #3276 is complete) | supported   |

When #3276 is complete the whole table above will say "supported".

**Comment by SueChaplain** [comment]
Thanks for the confirmation @fjeremic. Just out of interest, when was the compressed refs restriction removed for Hardware CS? Wondering how long the docs have been wrong.

**Comment by fjeremic** [comment]
> Thanks for the confirmation @fjeremic. Just out of interest, when was the compressed refs restriction removed for Hardware CS? Wondering how long the docs have been wrong.

Both compressedrefs and non-compressedrefs handrware accelerated concurrent scavenge has been supported since inception (sometime last year I believe).
