### ISSUE TITLE
Generate two sets of user documentation: "latest" and "last release"

### ISSUE THREAD

**Issue by SueChaplain** [eclipse/openj9-docs#176]
Our current documentation hosted at www.eclipse.org/openj9/docs contains the latest information for Eclipse OpenJ9. i.e. If you build an OpenJDK with OpenJ9 the docs reflect the features and capabilities in the latest level of code.

Many consumers are obtaining pre-built OpenJDK with OpenJ9 binaries from the AdoptOpenJDK project. Typically, they will be picking up the last release. The user documentation might be misleading for these users because they are reading about features/functions that are not available to them.

In order to support audiences for the "latest documentation" and "last release", we are proposing the following:

- change what is hosted at www.eclipse.org/openj9/docs to reflect the last release of OpenJ9
- start to host the draft content for the next release at the ghpages branch of this repository. 

Banners will be used to help people identify which documentation set they are looking at. We will also announce the change on the OpenJ9 website.

We have already included archives for each release of the documentation that can be downloaded and viewed offline for users who are on older releases than "last release".

Initial discussions with the project leads suggest they are in favour of this change. Please can you officially add your +1 here and we'll leave this open until the New Year for other contributors to comment if there are concerns. Otherwise we will look to make this change for 0.12.0.

@mstoodle @DanHeidinga @pshipton

**Comment by DanHeidinga** [comment]
> We have already included archives for each release of the documentation that can be downloaded and viewed offline for users who are on older releases than "last release".

@SueChaplain Can you add a link to the doc archives here?

**Comment by SueChaplain** [comment]
Doc archives: https://github.com/eclipse/openj9-docs/tree/master/downloads

**Comment by SueChaplain** [comment]
This work is now complete. Closing
