### ISSUE TITLE
Change shared cache directory default permission

### ISSUE THREAD

**Issue by hangshao0** [eclipse/openj9-docs#178]
**Issue or pull request number:**
https://github.com/eclipse/openj9/pull/4025

**Overview:**
The shared cache directory default permission has been changed on OpenJ9 and IBM SDK. No impact on users explicitly setting the cache directory permission using "-Xshareclasses:cacheDirPerm=".

1. On new cache directory:
Before this change: 
The default permission is 0777
After this change: 
Use 0777 if the cache directory is the default "/tmp/javasharedresources"
Use 0700 on new cache directory created without "groupAccess"
Use 0770 on new cache directory created with "groupAcess"

2. On existing cache directory: 
Before this change:
On Linux, AIX and OSX, we ensure the cache directory permission is always 0777
After this change:
On Linux, AIX and OSX, we ensure the cache directory permission is 0777 only when it is the default "/tmp/javasharedresources"

**Applies to the following JDK versions:**
Java 8 and Java 11

**Applies to the following platforms:**
All platforms except Windows

**For new command line options:**
N.A

- Purpose:
To make the shared cache directory more secure. 

- Restrictions:
N.A.

**Comment by doveye** [comment]
Hi @hangshao0 - I have some questions about part 2:

In the current docs (https://www.eclipse.org/openj9/docs/xshareclasses/#cachedirperm), we say the following under "cacheDirPerm":

> The permissions that are specified by this suboption are used only when you are creating a new cache directory. If the cache directory already exists, this suboption is ignored and the cache directory permissions are not changed.

But the issue description says that for existing directories before this change "we ensure the cache directory permission is always 0777".  Did something change previously and the docs are currently wrong?

How do we "ensure" the cache dir permissions of an existing dir? If the user changed the permissions of "/tmp/javasharedresources" to something else, does the VM change them back again (when it creates a new cache in that dir)?

**Comment by pshipton** [comment]
@doveye I don't think the doc is incorrect, perhaps just misleading. If a cacheDirPerm is specified then the directory permissions are not modified. If a cacheDirPerm is not specified, previously the directory permissions are modified to 0777 when a cache is opened.

"ensure the cache directory permission is always 0777" means the directory permissions are modified to 0777.

> If the user changed the permissions of "/tmp/javasharedresources" to something else, does the VM change them back again

Yes, but only when a cacheDirPerm is not specified. It is done when the cache is opened, a new cache doesn't need to be created.

**Comment by doveye** [comment]
@pshipton @hangshao0 
Thanks for the clarification Peter. I've added a section to the What's New topic for 0.12.0, and modified the Xshareclasses topic. 

Please review and let me know if any changes are required, thanks:

**What's New topic - new section:** 

![shrc-perm-whatsnew](https://user-images.githubusercontent.com/14108229/50907872-4c1d2c00-1420-11e9-8743-59323c9fc12b.jpg)

**-Xshareclasses topic:** 

I replaced the following sentence in the cacheDirPerm section with the table below (I assume the rest of that section still applies): 

> If you do not set this suboption, the cache directory permissions are set to 777, for compatibility with earlier Java versions.

New table:

![shrc-perm](https://user-images.githubusercontent.com/14108229/50906423-f72be680-141c-11e9-93b2-5dc88ab4cf64.jpg)

**Comment by doveye** [comment]
Thanks Peter :)
