### ISSUE TITLE
Shared classes disabled by default

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9-docs#187]
https://github.com/eclipse/openj9/pull/4227

**Overview:**
Due to a performance regression #4205, shared classes is no longer enabled by default. Nothing else changes, the default cache directory is still modified and the shared cache directory permissions remain the same.

**Applies to the following JDK versions:**
All

**Applies to the following platforms:**
All

**Comment by SueChaplain** [comment]
Doc changes backed out in https://github.com/eclipse/openj9-docs/pull/189
