### ISSUE TITLE
Documentation changes for openssl 1.0.2 and dynamic loading of crypto library

### ISSUE THREAD

**Issue by enasser** [eclipse/openj9-docs#188]
**Issue or pull request number:**
*https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/227*

**Overview:**
*Support for openssl 1.0.2p and above releases. The crypto library is not bundled by default. User can set the PATH or LIBPATH or LD_LIBRARY_PATH to crypto library if the library is not already in the system path*

**Applies to the following JDK versions:**
* 8 and 11*

**Applies to the following platforms:**
*All platforms *

**For new command line options:**

- Option name and syntax: **
- If values are set:  
	- Units for setting: **
	- Range: **
	- Default value: **
- Purpose:
- Restrictions:

**Comment by enasser** [comment]
For the release note of Java 11 and 12, the following statement need to be modified

> The OpenSSL V1.1.x implementation is enabled by default and supported for the Digest, CBC, and GCM algorithms. Binaries obtained from AdoptOpenJDK include OpenSSL v1.1.x (see Note).

The OpenSSL V1.0.2 and above are supported for the Digest, CBC, and GCM algorithms. The JDK binaries obtained from AdoptOpenJDK did not bundle openssl crypto library and expects openssl crypto library to be available in the system library path.

**Comment by enasser** [comment]
In the release note,  remove the second statement starting "Currently, OpenSSL is not bundled" as it is not relevant as we are not bundling openssl crypto library anymore and expect the system installed openssl.

> OpenJDK 8 with OpenJ9 includes OpenSSL support since V0.11.0. Currently, OpenSSL is not bundled as part of the AdoptOpenJDK AIX binaries due to an unresolved problem.

**Comment by enasser** [comment]
in https://www.eclipse.org/openj9/docs/introduction/#cryptographic-operations, modify the following statement:
> The OpenSSL V1.1.x implementation is currently supported for the Digest, CBC, and GCM algorithms.

The OpenSSL v1.0.2 and later releases are currently supported for the Digest, CBC, and GCM algorithms. The OpenSSL crypto library is not bundled with JDK and expects the library to be available in the system library path.

**Comment by enasser** [comment]
@SueChaplain These are the changes required for openssl v 1.0.2 support and not bundling the crypto library with adoptopenjdk binary. Please let me know if you have any questions.

**Comment by pshipton** [comment]
Note that although the jdk8 changes are merged to the head stream (but not yet the 0.12 release branch), the docs should not be changed before Adopt makes the change to stop bundling openssl.
