### ISSUE TITLE
xxinitialrampercentage page has a broken link

### ISSUE THREAD

**Issue by adamfarley** [eclipse/openj9-docs#197]
**Page containing the error:**

*https://www.eclipse.org/openj9/docs/xxinitialrampercentage/*

**Describe the error and the update needed:**

The container support link is broken.

Right now it links to here: https://www.eclipse.org/openj9/docs/xxinitialrampercentage/xxusecontainersupport

It seems like it *should* link to here: https://www.eclipse.org/openj9/docs/xxusecontainersupport/

**Comment by doveye** [comment]
I actually just found that, and a bunch of other broken links too :)  Thanks for reporting.

**Comment by doveye** [comment]
Fixed all broken links with https://github.com/eclipse/openj9-docs/pull/198

**Comment by adamfarley** [comment]
Thanks.
