### ISSUE TITLE
Print a javacore dump to STDOUT and STDERR 

### ISSUE THREAD

**Issue by AidanHa** [eclipse/openj9-docs#204]
https://github.com/eclipse/openj9/issues/2837#issuecomment-458884303
https://github.com/eclipse/openj9/pull/4521

**Overview:**
Give user options to print a javacore dump to STDOUT/ERR rather than printing to a file.

Applies to all JDK version

Applies to all platforms

-Xdump:java:file=/STDOUT/ 
-Xdump:java:file=/STDERR/ 

This option is non case sensitive (eg: `/stdout/` will also work.

You can also print to STDOUT with -Xdump:java:file=-

Add the option -Xdump:java:file=/STDOUT/ to print a javacore dump to STDOUT
Add the option -Xdump:java:file=/STDERR/ to print a javacore dump to STDERR

**Comment by pshipton** [comment]
eclipse/openj9#4521 has been merged.

**Comment by pshipton** [comment]
Modified to include `-` as another way to write to stdout.

**Comment by pmhayward** [comment]
@AidanHa, @pshipton  ... I'm currently modifying the -Xdump topic in the docs for this addition, but wanted to confirm the exact syntax - I think I've seen all of these variations mentioned in various comments!...
-Xdump:java:file=/STDOUT/
-Xdump:java:file=/STDOUT
-Xdump:java:file=STDOUT
Please confirm re the forward slash, which of these is allowed.
Also, is a dash (-) an abbreviation for just STDOUT, or is it (or something else) also an abbreviation for STDERR? (If it's for both, how do you distinguish?!)
Thanks!

**Comment by AidanHa** [comment]
Hi,

_Only_ following options print to stdout:
-Xdump:java:file=/STDOUT/
-Xdump:java:file=-

_Only the following print to stderr:
-Xdump:java:file=/STDERR/

The dash prints to std and is not an abbreviation :)

**Comment by pmhayward** [comment]
Thanks for clarification. (I didn't exactly mean 'abbreviation' - perhaps 'alternative' would have been a better word!)
