### ISSUE TITLE
Document jps

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/openj9-docs#210]
https://github.com/eclipse/openj9/pull/4650
**Overview:**
This adds the `jps` utility to OpenJ9 for compatibility with the reference implementation.

**Applies to the following JDK versions:**
Java 8 and later
**Applies to the following platforms:**
All platforms (limited support on z/OS)
**For new command line options:**
Command line syntax:
```
jps: Print a list of Java processes and information about them
-J: supply arguments to the Java VM running jps
-l: print the application package name
-q: print only the virtual machine identifiers
-m: print the application arguments
-v: print the Java VM arguments, including those produced automatically
```
This lists all running Java processes on the current host.
Limitations:

- Does not list Java processes on other hosts
- Does not list Java processes owned by other users
- Does not list non-OpenJ9 Java processes
- Does not list processes whose attach API is disabled.  Note that attach API is disabled by default on z/OS.

**Comment by SueChaplain** [comment]
Hi @pdbain-ibm 

I believe we would put this into the tools section of the user doc, since it doesn't fit well with the -X, -XX areas.

Your description states that you are adding the jps utility for compatibility, but reading through the issue it sounds like you have re-implemented the capability by using Attach API under the covers. As such we need to be careful how we introduce this to the user docs to avoid people assuming that the existing jps utility will work with OpenJ9.

I notice a small difference between the Oracle jps options and ours. No -V option? Any reason here?

We might have a few more questions for you when we come to do the work.

**Comment by pdbain-ibm** [comment]
Hi @SueChaplain 
You are correct that OpenJ9's `jps` is an approximation of the HostSpot implementation and is not guaranteed to behave identically.  You are correct the `-V` is not supported.  
Please contact me if you have other questions.

**Comment by doveye** [comment]
Hi @pdbain-ibm. Do you have an example command and output please? Especially for the use of some of the options, eg -J.

A couple of questions:
1. Does the tool list all the running processes for all the JVMs on the host (for this user)? Or does the user  have to pass the -Dcom.ibm.tools.attach.id=<process_ID> option via `jps -J` to specify a different JVM?
2. Is the output format the same as HotSpot, ie "lvmid [ [ classname | JARfilename | "Unknown"] [ arg* ] [ jvmarg* ] ]"?

**Comment by pdbain-ibm** [comment]
> Hi @pdbain-ibm. Do you have an example command and output please? Especially for the use of some of the options, eg -J.

Sure:

```
$ jps
5462 looper
14272 Jps
$ jps -l
5462 looper
14332 openj9.tools.attach.diagnostics.Jps
$ jps -q
5462
14476
```

The output for `-v` is quite verbose as it includes automatically generated JVM options; we are working on fixing that.

```
$ jps -v
5462 looper -Xoptionsfile=/home/pdbain/projects/jps/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/options.default -Xlockword:mode=default,noLockword=java/lang/invoke/ThunkTuple -Xjcl:jclse29 -Dcom.ibm.oti.vm.bootstrap.library.path=/home/pdbain/projects/jps/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs:/home/pdbain/projects/jps/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64 -Dsun.boot.library.path=/home/pdbain/projects/jps/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs:/home/pdbain/projects/jps/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64 -Djava.library.path=/home/pdbain/projects/jps/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs:/home/pdbain/projects/jps/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64:/usr/lib64:/usr/lib -Djava.home=/home/pdbain/projects/jps/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre -Djava.ext.dirs=/home/pdbain/projects/jps/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/ext -Duser.dir=/home/pdbain/projects/jps/openj9-openjdk-jdk8 -Djava.class.path=. -Djava.class.path=/home/pdbain/lib -Dsun.java.command=looper -q -Dsun.java.launcher=SUN_STANDARD -Dsun.java.launcher.pid=5462
```

`-J` is used like so: `jps -J-Xmx10m -J-Dsome.property=some_value`.
> 
> A couple of questions:
> 
> 1. Does the tool list all the running processes for all the JVMs on the host (for this user)? Or does the user  have to pass the -Dcom.ibm.tools.attach.id=<process_ID> option via `jps -J` to specify a different JVM?

Yes to the former: it will list all OpenJ9 JVMs owned by the user on the current host.

> 2. Is the output format the same as HotSpot, ie "lvmid [ [ classname | JARfilename | "Unknown"] [ arg* ] [ jvmarg* ] ]"?

Yes, though we don't guarantee exact correspondence.

**Comment by doveye** [comment]
Thanks @pdbain-ibm . I've made doc updates as follows (currently on staging server only: https://eclipse.github.io/openj9-docs-staging/214/), can you please review for technical accuracy (we're still debating the positioning of HotSpot-OpenJ9 comparison info):

1. Added a bit to "New to OpenJ9?" about tools added for compatibility (see para starting with "In other cases..."). That section links to....
2. "Switching to OpenJ9" - created a new topic for these tools, for HotSpot switchers. It mimics the one for command-line options. We can add jstat, jcmd etc here too when they are ready. This links to...
3. New topic, "Java process status", which covers the jps tool. Note: the bit about lvm_id being different in Cygwin came from a Google search. It would be good if you could confirm please :)

**Comment by pdbain-ibm** [comment]
@doveye 
A few comments:
In`Switching to OpenJ9`, "The main differences from the HotSpot jps tool are as follows:" there is a line break in the middle of `jps` on my browser.

In `Java process status`:
- instead of `lvm_id`, I would use `VMID` and say "VMID is the Attach API Virtual Machine identifier for the Java process"
- in "$ jps -l 5462 looper 14332 openj9.tools.attach.diagnostics.Jps", please change `looper` to `org.foo.bar.MyApplication`
- The examples are missing line breaks.  Please see 
https://github.com/eclipse/openj9-docs/issues/210#issuecomment-464805487
- In "The tool shows information for every Java process that is owned by your user, for every VM, on the current host", please delete "for every VM," as it is redundant.  
- Please also change "owned by your user" to "owned by the current userid"
- "3\. lvm_id being different in Cygwin": I am not aware of any such difference in OpenJ9.  However, the VMID may be different from the process ID if the process was launched with the system property `com.ibm.tools.attach.id` set.

**Comment by doveye** [comment]
Thanks @pdbain-ibm, I've made the updates. Ignore the colour coding on the examples, it's a general MkDocs (doc hosting solution) thing that we need to remove!

I am not seeing a line break in `Switching to OpenJ9` (on Firefox, Chrome, or IE), or anything in the Markdown that could cause it - which browser are you using? Is the line break still there if you refresh the page?

**Comment by pdbain-ibm** [comment]
I am using Safari.  Attached screenshot:
<img width="763" alt="screen shot 2019-02-20 at 11 20 46" src="https://user-images.githubusercontent.com/18007966/53106758-ab7f5900-3501-11e9-9267-cecc90615abb.png">

Everything else looks good.

**Comment by doveye** [comment]
Thanks @pdbain-ibm. Presumably if you resize the window you can get `jps` on one line? I think this could be either a bug in Safari (wrapping when it shouldn't) or in the css that is used by the MkDocs theme.

**Comment by pdbain-ibm** [comment]
Resizing the window to the point where the sidebar disappears cause correct wrapping, except at certain smaller sizes.  Odlly, thta it the only case of a line break mid-word.

**Comment by doveye** [comment]
Interesting. I'll raise an issue for us to investigate more later, but otherwise, I think this issue is done. I'll leave it open until the code work is complete.

**Comment by doveye** [comment]
I added a section to the What's New for 0.13.0 (only merged today), and the updates are now visible at https://eclipse.github.io/openj9-docs/version0.13/. Closing this issue.
