### ISSUE TITLE
Attach API VirtualMachine.getSystemProperties() adds sun.jvm.args

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/openj9-docs#216]
**Issue or pull request number:**
https://github.com/eclipse/openj9/pull/4650
**Overview:**
Attach API VirtualMachine.getSystemProperties() now includes system property `sun.jvm.args`.
This has been added to show all Java VM arguments, including both user-supplied and automatically-generated arguments, though this may be subject to change.

**Applies to the following JDK versions:**
Java 8 and 11 as of 0.13 (although 0.13 only ships Java 12)

**Applies to the following platforms:**
All platforms
**For new command line options:**
N/A

**Comment by doveye** [comment]
Hi @pdbain-ibm. From your comment here https://github.com/eclipse/openj9/issues/2377#issuecomment-465628879, it sounds like this was implemented to support the `jps` tool, presumably for the `-v` option? If so, I don't think any additional user doc is required. Maybe just an update to API doc (though I have no idea where that is generated in OpenJ9, and we didn't publish the Attach API before).

If the user can use the API directly to get info that would be helpful in other situations, we could maybe highlight it as an enhancement in its own right in What's New? (It would be helpful to point at the API doc, if that is available, or tell the user how to find the API doc in the built JDK, assuming it's there).

**Comment by pdbain-ibm** [comment]
> Hi @pdbain-ibm. From your comment here [eclipse/openj9#2377 (comment)](https://github.com/eclipse/openj9/issues/2377#issuecomment-465628879), it sounds like this was implemented to support the `jps` tool, presumably for the `-v` option? 

Correct.

> If so, I don't think any additional user doc is required. 

I concur.

> Maybe just an update to API doc (though I have no idea where that is generated in OpenJ9, and we didn't publish the Attach API before).

For the record, there is a bunch of documentation for IBM's (hence OpenJ9's) Attach API here and other places: 
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=2ahUKEwiW-c2N4MrgAhWim-AKHa0wB_AQFjAAegQIABAB&url=https%3A%2F%2Fwww.ibm.com%2Fsupport%2Fknowledgecenter%2Fen%2FSSYKE2_7.0.0%2Fcom.ibm.java.lnx.70.doc%2Fuser%2Fattachapi.html&usg=AOvVaw3GrUm0O-xnFbtnJ0U4ztjE, though we refer to third-party documantation for the javadoc.

> 
> If the user can use the API directly to get info that would be helpful in other situations, we could maybe highlight it as an enhancement in its own right in What's New? (It would be helpful to point at the API doc, if that is available, or tell the user how to find the API doc in the built JDK, assuming it's there).

Users can get the JVM arguments of the local machine via `java.lang.management.RuntimeMXBean.getInputArguments()`; this is standard API.

**Comment by doveye** [comment]
Thanks Peter. Closing this issue as no user doc updates required.
