### ISSUE TITLE
Document new command line option: -XX:OnOutOfMemoryError=<STRING>

### ISSUE THREAD

**Issue by sharon-wang** [eclipse/openj9-docs#242]
**Issue or pull request number:**
https://github.com/eclipse/openj9/pull/5239

**Overview:**
Add new command line option `-XX:OnOutOfMemoryError=<STRING>`, which maps to the existing OpenJ9 equivalent `-Xdump:tool:events=systhrow,filter=java/lang/OutOfMemoryError,exec=<STRING>`.

**Release target:**
Eclipse OpenJ9 0.15.0

**Applies to the following JDK versions:**
All JDK versions.

**Applies to the following platforms:**
All platforms.

**For new command line options:**

- **Option name and syntax:** `-XX:OnOutOfMemoryError=<STRING>`
- **Setting the `<STRING>` value:**  
	- `<STRING>` specifies the command(s) to run when a java.lang.OutOfMemoryError has occurred in the main program
	- `<STRING>` can be a single command or multiple commands, using semicolons to separate each command, eg. `-XX:OnOutOfMemoryError="<PATH_TO_JAVA> <JAVA_PROGRAM>; cat file.txt"`
	- **Example Usage:** `java -XX:OnOutOfMemoryError="java -version" Test`
		- Assuming that Test.java contains code that generates an OutOfMemoryError, `java -version` will be run when java.lang.OutOfMemoryError is thrown.
- **Purpose:** Provides the ability to run one or more commands when a java.lang.OutOfMemoryError is thrown.

**Comment by doveye** [comment]
The doc updates are in draft, @sharon-wang please review and let me know if any changes are required:

- What's new update: https://eclipse.github.io/openj9-docs-staging/282/version0.15/
- New topic: https://eclipse.github.io/openj9-docs-staging/282/xxonoutofmemoryerror/
- New row in table of HotSpot compatibility options: https://eclipse.github.io/openj9-docs-staging/282/cmdline_migration/

**Comment by sharon-wang** [comment]
Looks good to me. @pshipton would you mind having a look?

**Comment by pshipton** [comment]
Looks good.

**Comment by doveye** [comment]
Great, thanks :)  Changes now merged.
