### ISSUE TITLE
JVMTI watched field performance improvement

### ISSUE THREAD

**Issue by gacholio** [eclipse/openj9-docs#252]
**Issue or pull request number:**
*https://github.com/eclipse/openj9/pull/2258*

**Overview:**
*Provide a command line option to enable experimental performance improvements relating to JVMTI watched fields.*

**Release target:**
*Eclipse OpenJ9 0.14.0*

**Applies to the following JDK versions:**
*All*

**Applies to the following platforms:**
*x86 platforms (Windows and Linux)*

**For new command line options:**

- Option name and syntax: *-XX:[+|-]JITInlineWatches*
- Purpose: When enabled, JVMTI watched fields will cause less of a performance degradation.
- Restrictions: Only works on x86 platforms (Windows and Linux)

**Comment by DanHeidinga** [comment]
fyi @SueChaplain
