### ISSUE TITLE
Using multiple options for the -Xdump option

### ISSUE THREAD

**Issue by AidanHa** [eclipse/openj9-docs#256]
Hello, 

https://www.eclipse.org/openj9/docs/xdump

I've had an OpenJ9 user who has gotten confused with the use of multiple suboptions for the `-Xdump` option.

In the documentation, it does not explicitly say that multiple suboptions must be split with a comma. That being said, this user tried to print a javacore file to STDERR with the command:

`./java -Xdump:java:events=vmstart:file=/STDERR/ -version` 

where the actual command is:

`./java -Xdump:java:events=vmstart,file=/STDERR/ -version`

where each Xdump suboption after the dump agent suboption is separated with a comma instead of a colon. The user did not know that multiple suboptions must be separated with a comma.

I looked at the doc, and there was no where that explicitly says suboptions must be separated by commas. Thus we should include a line near the top of the page that explicitly mentions this

**Comment by SueChaplain** [comment]
That's a fair point, @AidanHa - syntax diagrams aren't well supported in the doc tool we are using. That is where we used to show the "," in the old documentation set. We must add some words and example to make this clear. BTW ... did your user try the Option Builder tool? This helps enormously with getting the syntax correct: https://www.eclipse.org/openj9/docs/xdump/#xdump-option-builder

**Comment by AidanHa** [comment]
They did not use the option builder... Regardless, I believe some sort of documentation regarding multiple suboptions should be available outside the option builder tool

**Comment by AidanHa** [comment]
As well, the Option builder tool doesn't support printing to STDOUT/ERR. The only way to print that is to list `/STDOUT/` as a custom file name, which is unintuitive.
