### ISSUE TITLE
Enable `-XX:+JITInlineWatches` by default on x86

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9-docs#258]
**Issue or pull request number:**
https://github.com/eclipse/openj9/pull/5598

**Overview:**
Enhanced field watch is enabled by default on x platforms.  Previously option was add in `0.14.0` for x platforms.

**Release target:**
Eclipse OpenJ9 0.15.0

**Applies to the following JDK versions:**
All

**Applies to the following platforms:**
X platforms

**For new command line options:**
Enabled by default

**Comment by SueChaplain** [comment]
Backed out to address 0.14.2

**Comment by SueChaplain** [comment]
Doc change complete for the 0.15.0 release.
