### ISSUE TITLE
OpenSSL ChaCha20-Poly1305 acceleration

### ISSUE THREAD

**Issue by jerrylui803** [eclipse/openj9-docs#259]
Issue or pull request number:
https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/164

Overview:
OpenSSL ChaCha20-Poly1305 acceleration is added

Applies to the following JDK versions:
jdk11

Applies to the following platforms:
All platforms

For new command line options:
Enabled by default.
The jdk.nativeChaCha20 system property can control ChaCha20-Poly1305 individually, similarly to the other algorithms.

**Comment by pshipton** [comment]
Note the same changes are required for jdk12 and jdk (head).

**Comment by SueChaplain** [comment]
@jerrylui803 

So we have -Djdk.nativeChaCha20, and -Dnative.Crypto will control this as well as all other algorithms.

Is this algorithm available on all supported OpenSSL versions, including 1.0.1, which I believe is being added at the moment?

When will JDK12 be done?
What about JDK8?

**Comment by ashbm5** [comment]
@SueChaplain 

There are no current plans to support this algorithm in JDK8.
The OpenSSL version that supports this algorithm is OpenSSL 1.1.1 only.
JDK12 - TBD

**Comment by doveye** [comment]
@ashbm5 did this get done for JDK12 please?
@jerrylui803 - https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/164 mentions ChaCha20 and ChaCha20-Poly1305. This [IETF doc](https://tools.ietf.org/html/rfc7539) lists those as two separate algorithms, and also mentions Poly1305 as a third algorithm. Can you please clarify how many algorithms  we are talking about for this issue (and which ones!), so we can get the terminology correct, thanks.

**Comment by ashbm5** [comment]
@doveye this function has not been ported to JDK12, there are two algorithms implemented: ChaCha20 and also ChaCha20-Poly1305. The poly1305 hashing algorithm is not supported.

**Comment by pshipton** [comment]
Note the chance is ported to Java 13+.

**Comment by doveye** [comment]
Draft doc updates are ready - @jerrylui803  and/or @ashbm5  can you please review and let me know if anything needs changing, thanks:
- Section in What's New for 0.15: https://eclipse.github.io/openj9-docs-staging/283/version0.15/
- New topic for -Djdk.nativeChaCha20: https://eclipse.github.io/openj9-docs-staging/283/djdknativechacha20/
- Added to lists of algorithms in https://eclipse.github.io/openj9-docs-staging/283/djdknativecrypto/ and  https://eclipse.github.io/openj9-docs-staging/283/introduction/#cryptographic-operations

**Comment by pshipton** [comment]
lgtm

**Comment by ashbm5** [comment]
@doveye in https://eclipse.github.io/openj9-docs-staging/283/version0.15/#chacha20-algorithm-support-for-openssl 

instead of "The ChaCha20 and ChaCha20-Poly1305 algorithms are now supported on Java 11" how about "The ChaCha20 and ChaCha20-Poly1305 algorithms can now leverage OpenSSL on Java 11".

otherwise looks good.

**Comment by doveye** [comment]
Thanks for the reviews. I made @ashbm5's change (except I used "use" instead of "leverage", as it's a simpler word :) ). Docs now published.
