### ISSUE TITLE
Documentation updates for software CS on Z

### ISSUE THREAD

**Issue by NigelYiboYu** [eclipse/openj9-docs#261]
**Issue or pull request number:**
*https://github.com/eclipse/openj9/pull/5183*
*https://github.com/eclipse/omr/pull/3680*

Related to PPC issue: https://github.com/eclipse/openj9-docs/issues/134

**Overview:**
Software concurrent scavenge on z has been delivered to OMR and OpenJ9, we need to update documentation of pauseless GC on Z.
According to https://github.com/eclipse/openj9-docs/issues/134#issuecomment-444111197, the existing doc on ConcurrentScavenge is in the following topics:

https://www.eclipse.org/openj9/docs/xgc/#concurrentscavenge
https://www.eclipse.org/openj9/docs/gc/

**Release target:**
*N/A*

**Applies to the following JDK versions:**
*8 and later*

**Applies to the following platforms:**
*Linux Z and z/OS*

**For new command line options:**

- Option name and syntax: *-XXgc:softwareRangeCheckReadBarrier. May also need -Xgc:concurrentScavenge*

- Purpose: Enable software-based concurrent scavenge on Z systems running on z13 and below CPUs.

- Restrictions: N/A

**Comment by NigelYiboYu** [comment]
@fjeremic @gita-omr FYI, this is to track Z software concurrent scavenge documentation update.

**Comment by NigelYiboYu** [comment]
I've drafted a pull request for software CS on z: https://github.com/eclipse/openj9-docs/pull/262
Can somebody review? @fjeremic @SueChaplain 
FYI @amicic

**Comment by amicic** [comment]
We should document this behavior (see the PR comment): https://github.com/eclipse/omr/pull/3094.
And, of course, verify that it still holds.

**Comment by SueChaplain** [comment]
Closing, see PR #262
