### ISSUE TITLE
Add information on using Transparent HugePage options

### ISSUE THREAD

**Issue by fengxue-IS** [eclipse/openj9-docs#273]
**Issue or pull request number:**
*https://github.com/eclipse/omr/pull/3647*
*https://github.com/eclipse/openj9/pull/6013*

**Release target:**
*Eclipse OpenJ9 0.15.0*

**Applies to the following JDK versions:**
*8 and later*

**Applies to the following platforms:**
*Linux X|P|Z*

This code change adds support for Transparent HugePage to be used when system setting is set to `Madvise`. This by default tries to mark all memory allocated though OMR as `MADV_HUGEPAGE` (ie. *promote to hugepage*). 

This should be included to the upcoming release note

~~Note: Currently the OpenJ9 `-X` option for controlling/overriding this configuration have not yet been added and will have a new command line option doc to be added in the future.~~

New OpenJ9 command line option `-XX:+/-TransparentHugePage` has been added (PR review process) to control the behaviour when TransparentHugePage (THP) is set to `madvise` on the system. (Note this option will be ignored on machines without THP or THP set to `always` or `never`)

The default setting for this option is set to `-XX:+TransparentHugePage` for performance reasons

**Comment by DanHeidinga** [comment]
fyi @vijaysun-omr

**Comment by SueChaplain** [comment]
@fengxue-IS Querying the release target as 0.14.2 is done and ready. Did this get missed, or is it really targeting 0.1.5.0

@pshipton FYI/comment

**Comment by pshipton** [comment]
This change is not in 0.14.2, it will be in 0.15

**Comment by fengxue-IS** [comment]
updated to 0.15.0, Thanks for the info @pshipton

**Comment by fengxue-IS** [comment]
FYI @SueChaplain 
The Information have been updated to include a new `-XX` command line option. code change is currently under review, will update this issue once that have been merged

**Comment by SueChaplain** [comment]
Thanks @fengxue-IS - will keep a watch out

**Comment by fengxue-IS** [comment]
Update, the PR for -XX commandline option have been merged

**Comment by pshipton** [comment]
Created https://github.com/eclipse/openj9/pull/6157 to modify the default to be -XX:-TransparentHugePage due to a footprint regression caused by using -XX:+TransparentHugePage as the default.

**Comment by SueChaplain** [comment]
@fengxue-IS - please can you review the doc changes in PR #302. A draft is staged here: https://eclipse.github.io/openj9-docs-staging/302/

**Comment by fengxue-IS** [comment]
@SueChaplain I've suggest some wording changes to avoid confusions. The doc looks great overall, thanks
