### ISSUE TITLE
Java 8 tools.jar updated

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/openj9-docs#275]
**Subject:**
The Attach API internal interfaces have changed slightly, affecting both the JDK's internal class library and `tools.jar`. 
**Suggestion:**
 Applications which make copies of tools.jar should ensure that it matches the current JDK.

This affect Java 8 only.

**Comment by SueChaplain** [comment]
@pdbain-ibm - trying to understand this one. I see the following 2 comments in the OpenJ9 PR:

>One possibility is to add an option for using the global namespace, so user's have to opt in, and understand the consequences.

>Or use the global namespace by default, but provide an option to use the original namespace when trying to communicate with older JVMs.

Sounds as if both are implemented .. one for OpenJ9 and one for behaviour with the IBM SDK? Please can you expand the explanation to help me work out what to write and what modifications might be needed for the IBM docs. Also, this option, is it an option you use with the API? Will the API doc be regenerated?

**Comment by pdbain-ibm** [comment]
@SueChaplain 
Thank you for your question. Actually, neither is implemented.

First, a clarification: the session/global distinction applies only to Windows, though there were some internal API changes to accommodate this.

Second, this change should be mostly invisible to users.  Internally, a JDKs with this change indicates via a property in the advertisement file that it is using the global semaphore.  Legacy JDKs are missing this property.  Newer JDKs check for this property and will use the global or session namespace depending on whether the property is present or absent respectively.

The only user-visible effect of this change is that older  JDKs may not be able to attach to newer JDKs.  Note that this is a restriction on the attach API in general.

The intent of this documentation change is that if a Java 8 application on any platform has a private copy of `tools.jar`, the application may be unable to use the attach API if it is using a newer JDK since the Java classes will not match.  Again, this is a general restriction: applications should use the `tools.jar` from the JDK.

**Comment by pshipton** [comment]
Note healthcenter.jar contains copies of attach classes from the tools.jar , Only an updated copy of healthcenter.jar should be used, once it is available.

**Comment by SueChaplain** [comment]
@pshipton will you be happy with this mentioned in the release notes in the "limitations" table. There is no natural fit in the user docs and it doesn't sound like an issue that needs to be called out in the What's new?

**Comment by pshipton** [comment]
@SueChaplain sounds good

**Comment by SueChaplain** [comment]
Addressed in https://github.com/eclipse/openj9/pull/6269 as a limitation.
