### ISSUE TITLE
UseGCStartupHints option

### ISSUE THREAD

**Issue by amicic** [eclipse/openj9-docs#290]
https://github.com/eclipse/openj9/issues/3743
https://github.com/eclipse/openj9/pull/6059

New option to enable/disable use of GC hints for initial (startup) heap sizing, as read/stored from/to Shared Cache.

Release target:
Eclipse OpenJ9 0.15.0

Option name and syntax: -XX[+|-]UseGCStartupHints

By default, the feature is disabled.

**Comment by amicic** [comment]
@pshipton @DanHeidinga

**Comment by DanHeidinga** [comment]
FYI @SueChaplain 

This option is shipping in the 0.15.0 release

**Comment by SueChaplain** [comment]
Thanks - there is minimal content in this issue, so hopefully I can find more by looking in to the related issues.

- purpose / why a user would want to enable it
- what happens behind the scenes
- how the data is used for (subsequent?) startups
- any restrictions .... spotted something about not in place for balanced?

**Comment by DanHeidinga** [comment]
@amicic Can you provide the details to Sue's queries above?

**Comment by amicic** [comment]
1) If a user is concerned with footprint, particularly due to heap sizing, it would typically set only -Xmx value but not -Xms value and let heap dynamically resize (based on GC heuristics that monitor GC overhead). If not explicitly specified, initial -Xms value is very small (8M). With medium and large workloads heap - would eventually grow into 100s of MB or even much more. However it would take a number of GCs during early phases of the run for heap to expand to anywhere close to a stable state. Those extra GCs impose startup overhead (delay). 
Then, the user would have a choice to manually set a larger -Xms value to avoid frequent GCs during startup, but -Xms value still small enough to preserve heap savings. However, it's time consuming for the user to determine reasonable -Xms values (or worse, they might not be aware of GC startup overhead) to balanced between startup savings and heap sizing.
With  UseGCStartupHints option enabled, JVM will through several (typically around 5) (re)starts learn itself what is reasonable -Xms is, adjust to it.

2) VM at 'startup complete' event will record current heap sizing and store 'hints' into Shared Cached. During subsequent (re)starts of VM will read this value very early (just after SC is available and initial heap is created)  and expand heap based on history values. Some historic averaging/smoothing is involved, which  makes the process of learning gradual (as mentioned, it takes ~5 restarts for hints to stabilize.
'Startup complete' event is issued when there noticeable drop in JIT activity (@DanHeidinga please, comment if this is reasonable correct, and/or if this is already documented elsewhere in more detail).

3) Sort of explained in 2. Feel free to ask here or DM me for more info, if needed.

4) The 'key' for accessing the hints is the full command line (explicitly and implicitly specified command line options). Whenever a hint is stored in SC, the key is stored along. Upon subsequent JVM restarts, the command line must fully match to the one stored in SC to be able to consume the hint - even the order of options must match. In future, we may add a way to ignore specific options (for example, a user may have options that contain a date/time as part of a log file name, which would make the key to mismatch on every restart). More than one part of key/hint can be store into SC. The only limit is the size of SC. Hence in a heterogeneous multi JVM environment (for example one server and several clients) running within one OS instance, each of JVMs would learn and use its own hints, as long each of VMs is restarted with command line options as in previous restarts.
(this sort of belongs to 1), too) For generational heap configurations (with Nursery, which has -Xmn group of options). Nursery sizing done independently from the sizing of the rest of the heap. Consequently, sizing hints are stored/consumed separately. Specifically, for Gencon GC policy we will maintain 2 hints: for Tenure and Nursery. True even if only -Xmx is specified, but -Xmnx can also be specified if the user  expects that fully loaded JVM will grow Nursery to  a different fraction of total heap size than what default is (1/4).
During starutp, verbose GC will report heap expansion with reason string "hint from previous runs". Example for gencon showing that heap is expanded w:
<heap-resize id="2" type="expand" space="nursery" amount="205258752" count="1" timems="0.328" reason="hint from previous runs" timestamp="2019-06-05T13:26:32.021" />
<heap-resize id="3" type="expand" space="tenure" amount="692649984" count="1" timems="0.326" reason="hint from previous runs" timestamp="2019-06-05T13:26:32.022" />
No visible log in GC is issued when hints are stored.

For Balanced GC (what is the only other generational GC policy in OpenJ9), this feature is not available, yet.

**Comment by DanHeidinga** [comment]
For this item, I think we can talk about the startup complete event and not worry about documenting when / how that is determined.

> 'Startup complete' event is issued when there is noticeable drop in JIT activity (@DanHeidinga please, comment if this is reasonable correct, and/or if this is already documented elsewhere in more detail).

The phase decisions are driven by the JIT.  @mpirvu has been documented elsewhere already?

**Comment by mpirvu** [comment]
No, we haven't documented the heuristics behind the phase detection mechanism. They are somewhat complex and involve several factors including:
- Samples falling on interpreted methods vs jitted methods
- Class loading acyivity
- Number of compilations
- CPU utilization
