### ISSUE TITLE
System OpenSSL documentation applicable to more than Java 12.

### ISSUE THREAD

**Issue by joransiu** [eclipse/openj9-docs#293]
**Page containing the error:**

https://www.eclipse.org/openj9/docs/adoptopenjdk/

**Describe the error and the update needed:**

Under Installation Pre-requisites, the following paragraph is tagged with "Java 12".

> OpenJDK binaries for Linux and AIX platforms from the AdoptOpenJDK community no longer bundle the OpenSSL cryptographic library. The library is expected to be found on the system path. If you want to use OpenSSL cryptographic acceleration, you must install OpenSSL 1.0.2 or 1.1.X on your system. If the library is not found on the system path, the in-built Java crytographic implementation is used instead, which performs less well.

My understanding from Alon is that this is applicable to Java 8, 11 drivers as well.   Will ask him to confirm on this issue.

**Comment by ashbm5** [comment]
@joransiu yes OpenJ9 for JDK8 and JDK11 will also attempt to dynamically load pre-installed openssl binaries

see ibmruntimes/openj9-openjdk-jdk11#135 and ibmruntimes/openj9-openjdk-jdk8#227

**Comment by pshipton** [comment]
The "Java 12" tag was correct for the 0.13 release of Java 12, which proceeded a release for all platforms. When 0.14 was released, the tag should have been removed.
