### ISSUE TITLE
OpenSSL MessageDigest is disabled (again)

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9-docs#294]
**Issue or pull request number:**
https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/318
https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/190
https://github.com/ibmruntimes/openj9-openjdk-jdk12/pull/59

**Overview:**
OpenSSL MessageDigest is disabled. We've done this and documented this before.
The system property jdk.nativeDigest cannot be used to enable MessageDigest.

**Release target:**
Eclipse OpenJ9 0.15 and later

**Applies to the following JDK versions:**
jdk8, jdk11, jdk12 so far. May do this for jdk13 and head later if necessary, but these are not included in the 0.15 release.

**Applies to the following platforms:**
All

**Comment by SueChaplain** [comment]
@pshipton  - this is confusing. We documented that Digest was disabled for 8 & 11 in 0.14.2 but we didn't document that Digest was disabled on JDK 12 in 0.14.2. This changes seems to prevent Digest being turned back on, but please confirm when this was disabled in JDK 12 ... for 0.15? I can't find a PR for it in the extensions repo.

**Comment by pshipton** [comment]
@SueChaplain we didn't disable Digest for JDK12 0.14.x because there was no JDK12 0.14.x release. The PR to disable it for 0.15 is in the initial description.

**Comment by SueChaplain** [comment]
Erm ≥.. 

These are effectively the same as the PRs for 0.14.2 but applied to head? i.e not doing something different?

ibmruntimes/openj9-openjdk-jdk8#318
ibmruntimes/openj9-openjdk-jdk11#190

**Comment by pshipton** [comment]
> These are effectively the same as the PRs for 0.14.2 but applied to head? i.e not doing something different?

Correct.
