### ISSUE TITLE
-Xdiagnosticscollector option removed

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9-docs#298]
**Issue or pull request number:**
https://github.com/eclipse/openj9/pull/5882

**Overview:**
See https://www.eclipse.org/openj9/docs/xdiagnosticscollector/
The option is now removed and the JVM gives an error.
`JVMJ9VM007E Command-line option unrecognised: -Xdiagnosticscollector`

**Release target:**
Eclipse OpenJ9 0.15.0

**Applies to the following JDK versions:**
All

**Applies to the following platforms:**
All

**Comment by doveye** [comment]
I removed the -Xdiagnosticscollector topic and added a section in the 0.15.0 release notes to tell users that it's gone.
