### ISSUE TITLE
Add watched fields support for Z systems

### ISSUE THREAD

**Issue by dchopra001** [eclipse/openj9-docs#304]
**Issue or pull request number:**
*https://github.com/eclipse/openj9/pull/4743*

**Overview:**
*Improved performance for watched fields for Linux on Z and z/OS systems. Support can be enabled with the existing `-XX:+JITInlineWatches` command line option.*

**Release target:**
*Eclipse OpenJ9 0.15.0*

**Applies to the following JDK versions:**
*8 and later*

**Applies to the following platforms:**
*Z*

- Purpose: To improve watched fields support for Java on Z platforms.

**Comment by dchopra001** [comment]
@SueChaplain FYI

**Comment by doveye** [comment]
Added z/OS and Linux on z to the existing release note about JITInlineWatches being on by default (https://eclipse.github.io/openj9-docs/version0.15/#performance-improvements-for-jvmti-watched-fields), and changed the support statement in the -XX:JITInlineWatches topic (https://eclipse.github.io/openj9-docs/xxjitinlinewatches/).
