### ISSUE TITLE
Improve performance of Field Watch support on Power

### ISSUE THREAD

**Issue by gita-omr** [eclipse/openj9-docs#305]
**Issue or pull request number:**
eclipse/openj9#6234

**Overview:**
Improved performance for watched fields on Power systems. Support can be enabled with the existing -XX:+JITInlineWatches command line option.

**Release target:**
Eclipse OpenJ9 ~~0.15.0~~ 0.16.0

**Applies to the following JDK versions:**
8 and later

**Applies to the following platforms:**
Power

    Purpose: To improve performance of watched fields support for Java on Power platforms by enabling it for JIT compiled methods.

**Comment by gita-omr** [comment]
@SueChaplain this feature was moved to 0.16.

**Comment by doveye** [comment]
@gita-omr - when you say Power, do you mean Linux on IBM Power Systems as well as AIX?

**Comment by doveye** [comment]
@gita-omr  Hi Gita, can you please confirm whether this item is for Linux on IBM Power Systems as well as AIX?

**Comment by gita-omr** [comment]
> 
> 
> @gita-omr Hi Gita, can you please confirm whether this item is for Linux on IBM Power Systems as well as AIX?

Yes, it's for Linux and AIX.

**Comment by doveye** [comment]
@gita-omr  Thanks for the update. I've added a section to the What's New (https://eclipse.github.io/openj9-docs/version0.16/#performance-improvements-for-jvmti-watched-fields-on-power-systems), and removed the restriction on https://eclipse.github.io/openj9-docs/xxjitinlinewatches/.
