### ISSUE TITLE
Enable bootstrap class sharing by default

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9-docs#311]
**Issue or pull request number:**
https://github.com/eclipse/openj9/pull/6271

**Overview:**
Shared classes, bootstrap classes only, is enabled by default. As it was temporarily once before.
https://www.eclipse.org/openj9/docs/xshareclasses/#bootclassesonly
https://github.com/eclipse/openj9-docs/issues/110
https://github.com/eclipse/openj9-docs/issues/149

**Release target:**
Eclipse OpenJ9 0.16.0

**Applies to the following JDK versions:**
all

**Applies to the following platforms:**
all

**Comment by doveye** [comment]
Updates are now on the staging server, could you please review, thx:
- New section in 0.16 release notes: https://eclipse.github.io/openj9-docs-staging/335/version0.16/
- Re-enabled the text we had before for the class data sharing topic (and tweaked slightly), in the "Enabling class data sharing" section: https://eclipse.github.io/openj9-docs-staging/335/shrc/
- Also added a mention at the topi of the -Xshareclasses topic: https://eclipse.github.io/openj9-docs-staging/335/xshareclasses/

**Comment by doveye** [comment]
Hi @pshipton, have you had a chance to look at this yet please? (I know you've been on holiday for a while, so maybe not :)  )

**Comment by pshipton** [comment]
Sorry, I missed this somehow.

https://eclipse.github.io/openj9-docs-staging/335/version0.16/
`You can use the -Xshareclasses option`. -Xshareclasses should be a link to the command line doc.
Similarly in the `Enabling class data sharing` section. https://eclipse.github.io/openj9-docs-staging/335/shrc/

Not sure the suggestion to enable j9shr.2271 is the best way. This seems like advanced / developer usage. We don't explain how to enable this tracepoint, or how to interpret the results. It also doesn't help explain why the shared cache didn't start if there is a problem. I prefer to suggest that users run with `-Xshareclasses:bootClassesOnly` or `-Xshareclasses:bootClassesOnly,nonFatal` as desired.

@hangshao0

**Comment by hangshao0** [comment]
https://eclipse.github.io/openj9-docs-staging/335/version0.16/

`You can use the -Xshareclasses option to change the default behavior.`

Probably we can mention `-Xshareclasses:none` here as well which turns off class data sharing completely.

**Comment by doveye** [comment]
Thanks for the reviews. I made the changes but staging seems to be broken for this particular PR, so I'll add them here.

version0.16:

> Class data sharing is enabled by default for bootstrap classes, unless your application is running in a container. You can use the -Xshareclasses option to change the default behavior, including using -Xshareclasses:none to disable all class data sharing. For more information, see Class data sharing.

I left "Class Data Sharing" as the only link, becase the -Xshareclasses topic doesn't actually have that  much info about enabling, as it's a reference topic. The aim is for users to read "Class data sharing", then follow links in that topic to the -Xshareclasses topic. I did add the link Peter mentioned in the "Class data sharing" topic though.

shrc:

I added a couple of sentences to the end of the Enabling section to add a bit more info about enabling and disabling:

> Class data sharing is enabled by default for bootstrap classes only (the equivalent of specifying -Xshareclasses:bootClassesOnly,nonFatal,silent), unless your application is running in a container. You can use the -Xshareclasses option to change the default behavior, for example you can change the name and location of the default shared classes cache. To enable class data sharing for non-bootstrap classes as well, use -Xshareclasses without the bootClassesOnly suboption. You can also disable all class data sharing by using the none suboption.

Re the j9shr.2271 tracepoint - I just removed that info. The user should be able to figure out how to use j9shr.2271 from the -Xtrace doc, but if the results need interpretation then I agree it might not be that helpful. I believe that if the cache can't start, the user will see messages to tell them as much, and to advise about using nonFatal, so we probably don't need to mention that again here.

**Comment by pshipton** [comment]
> I believe that if the cache can't start, the user will see messages to tell them as much

Since the default is `-Xshareclasses:bootClassesOnly,nonFatal,silent` which includes `silent`, there won't be any messages. If the users wants to see the messages related to the default cache, they should run with `-Xshareclasses:bootClassesOnly,nonFatal`

**Comment by doveye** [comment]
Ok, I've tweaked that section again: https://eclipse.github.io/openj9-docs-staging/335/shrc/#enabling-class-data-sharing

Hopefully this is ok now. I'm going to get the PR merged so that the info is there for Milestone 1, but if you spot anything else that needs changing, please let me know.

**Comment by pmhayward** [comment]
PR #335 now merged so closing this issue.
