### ISSUE TITLE
UseGCStartupHints enabled by default

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9-docs#324]
**Issue or pull request number:**
https://github.com/eclipse/omr/pull/4079
https://github.com/eclipse/openj9/issues/3743

**Overview:**
-XX:+UseGCStartupHints is enabled by default. Also note #311

**Release target:**
0.16

**Applies to the following JDK versions:**
all

**Applies to the following platforms:**
all

**Comment by doveye** [comment]
@pshipton - a couple of questions:
1. What happens if the user sets an initial heap size themselves, ie with -Xms or -XX:InitialHeapSize? 
2. I guess this doesn't work if shared classes is disabled? I see you've mentioned #311, so shared classes is enabled by default now, but just checking as I think it's worth highlighting in docs.

**Comment by doveye** [comment]
@amicic - I just posted a couple of questions for Peter but I think he's on vacation - could you take a look instead please? Thanks!

**Comment by amicic** [comment]
1. Still works even if initial heap size is set. Default scenario (with no initial size set), could be considered as if someone provided initial heap, just set it to size 8M. But than, size could be set to any other value. If it's very large , than hints are probably be no larger than the provided initial size.

2. SC must be enabled for hints to work. There are preserved in SC across VM restarts.

**Comment by doveye** [comment]
Thanks @amicic. I've made the following doc updates:
- added a section for this change to the 0.16.0 release notes topic
- updated the -XX:UseGCStartupHints topic (the only changes are the position of the tick in the table and the Notes section)

Could you please have a quick look and let me know if anything needs changing - you can get to both topics from https://eclipse.github.io/openj9-docs-staging/334/version0.16/. Thanks!

**Comment by doveye** [comment]
Hi @amicic. Any chance you could take a look at this please, or point someone else at it :)

**Comment by smlambert** [comment]
In @amicic 's vacation absence, @dmitripivkine can you have a look at the staged doc?

**Comment by dmitripivkine** [comment]
LGTM

**Comment by doveye** [comment]
Thanks both! Closing...
