### ISSUE TITLE
Document jcmd

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/openj9-docs#333]
**Subject:**
jcmd: run a diagnostic command on another Java process
**Suggestion:**

```
Format:
    jcmd <vmid> <arguments>
 Arguments:
    <vmid>: Attach API VM ID as shown in jps or other Attach API-based tools.
    command[command arguments]: command from the list returned by "-help"
    -help: print the list of diagnostic commands
    -J: supply arguments to the Java VM running jcmd
 NOTE: this utility may significantly affect the performance of the target JVM.
     The available diagnostic commands is determined by
     the target VM and may vary between VMs.

The target process must be running on the local machine and be owned by the current user.
```

**Release target:**
jcmd is already included in 0.16 with a subset of commands. There may be more sub-commands added before the code branch occurs for 0.16

**Applies to the following JDK versions:**
All

**Applies to the following platforms:**
All

The development issue is https://github.com/eclipse/openj9/issues/5164

**Comment by pshipton** [comment]
fyi https://github.com/eclipse/openj9/issues/6780

**Comment by doveye** [comment]
Hi @pdbain-ibm (fyi @pshipton). I've started some draft doc but have guessed some of the content. Please can you take a look, if you have time before the 23rd :)

- https://eclipse.github.io/openj9-docs-staging/341/version0.16/: added a What's New section
- https://eclipse.github.io/openj9-docs-staging/341/tool_migration/: added a section for main differences from HotSpot - I got this from online info so it does need checking
- https://eclipse.github.io/openj9-docs-staging/341/tool_jcmd/: The actual command topic. I have made some assumptions/guesses:
    - I assume you can use this command on multiple VMs?
    - I'm not sure the current command help is clear, so I've used slightly different syntax
    - This sentence came from our jmap topic. Is it also valid for jcmd? "VMIDs of dead processes are silently ignored."
    - I'm not sure the example syntax is correct - "jcmd 31452 Dump.heap"?
    - I assume the list of limitations at the bottom is accurate? It was copied from other j-tools topics

**Comment by pdbain-ibm** [comment]
Will do today.  Thanks.
fyi @pdbain and @jasonfengj9

**Comment by pshipton** [comment]
The command syntax shows `vmid` in lower case, but the explanation shows `VMID` in upper case in the command line reference and the migration topic.

The example `jcmd 31452 Dump.heap` isn't complete because `Dump.heap` requires a parameter, which is the dump file name. `jcmd 31452 Dump.heap myHeapDump`

Not sure why `Perfcounter.print` is called out explicitly. There are many other options which are not supported, some of which may be implemented by OpenJ9 in the future.

**Comment by pdbain-ibm** [comment]
- `I assume you can use this command on multiple VMs?`: not on this tool.

- `I'm not sure the example syntax is correct - "jcmd 31452 Dump.heap"?`: you need a file path as well.  FYI, to get help on that command use `jcmd 31452 help Dump.heap`. An example of a command without an argument would be `jcmd 31452 Thread.print`
- Note that the list of available diagnostic commands depends on the target VM as specified by <vmid> and may vary.


https://eclipse.github.io/openj9-docs-staging/341/version0.16/:
- `New Java command (jcmd) tool`: suggest changing to `New Java diagnostic command (jcmd) tool`.  Same comment for https://eclipse.github.io/openj9-docs-staging/341/tool_migration/
- `OpenJ9 now includes an independent implementation of the jcmd tool, for running diagnostic commands on a VM`.  I suggest removing the comma after "tool".

https://eclipse.github.io/openj9-docs-staging/341/tool_migration/:
- `Runs diagnostic commands on a specified VM or VMs.` . jcmd does not support multiple VMs, so `... on a specified VM.` would be more appropriate.
- In lieu of "There is no -foo option", I would say "The -foo option is not currently supported", as we plan to include these features eventually.

https://eclipse.github.io/openj9-docs-staging/341/tool_jcmd/:
- @jasonfengj9 has updated the command syntax, and a few more changes are anticipated, cf. https://github.com/eclipse/openj9/issues/6796
- `You can specify multiple VMIDs, separated by a space. VMIDs of dead processes are silently ignored.` Please remove this as it does not apply to this tool.
- the documentation for `-J` refers to `jps`. 
- `I assume the list of limitations at the bottom is accurate?`: yes

**Comment by pdbain-ibm** [comment]
> Not sure why `Perfcounter.print` is called out explicitly. There are many other options which are not supported, some of which may be implemented by OpenJ9 in the future.

It is specifically mentioned in the reference implementation `jcmd -h`  output.

**Comment by SueChaplain** [comment]
I thought I saw that this was moved to the 0.18 milestone. Did I get this wrong?

**Comment by pshipton** [comment]
> I thought I saw that this was moved to the 0.18 milestone. Did I get this wrong?

jcmd is already delivered. Any open issues that moved are for future work to add additional options or new tools.

**Comment by JasonFengJ9** [comment]
https://eclipse.github.io/openj9-docs-staging/341/version0.16/
```
  jcmd [<options] [<vmid> <arguments>]
```
Current OpenJ9 `jcmd help` output looks like https://github.com/eclipse/openj9/issues/6780#issuecomment-523161278.
There is an on-going discussion about what format it should be at https://github.com/eclipse/openj9/issues/6796.

**Comment by doveye** [comment]
Thanks for the reviews, updates are now visible :) 

Re 

> Note that the list of available diagnostic commands depends on the target VM as specified by and may vary.

Yep, there is text in the argument explanation to cover this:  "help: shows the diagnostic commands that are available for this VM. This list of commands can vary between VMs."

Re Perfcounter.print - I went through the synopsis of the HotSpot jcmd (https://docs.oracle.com/javase/8/docs/technotes/tools/windows/jcmd.html) to try and figure out what the main diffs were.

I heard that the required extensions are done for 8, 11, and 12, but not yet 13. We'll need to add something in the docs to tell users this isn't available on 13 if that remains the case when we GA, so if someone could post status in this issue, that would be great, thanks.

**Comment by pshipton** [comment]
@pdbain-ibm please create the jcmd launcher PR for https://github.com/ibmruntimes/openj9-openjdk-jdk13

**Comment by pdbain-ibm** [comment]
Already done back in July: https://github.com/ibmruntimes/openj9-openjdk-jdk13/blob/openj9/closed/make/closed_make/launcher/Launcher-jdk.jcmd.gmk

**Comment by pshipton** [comment]
Ok, I didn't find the PR (https://github.com/ibmruntimes/openj9-openjdk-jdk13/pull/7) because it only refers to jmap.

**Comment by doveye** [comment]
So the 13 work is done?

**Comment by pshipton** [comment]
jcmd was documented, see https://www.eclipse.org/openj9/docs/tool_jcmd/
