### ISSUE TITLE
Document new command line options: -XX:[+/-]ShareAnonymousClasses

### ISSUE THREAD

**Issue by sogutbera** [eclipse/openj9-docs#336]
**Issue or pull request number:**
https://github.com/eclipse/openj9/pull/6541

**Overview:**
Add new command line options -XX:[+/-]ShareAnonymousClasses, which allow to enable and disable storing and finding classes created through Unsafe.defineAnonymousClass (VM anonymous classes) in the shared class cache

**Release target:**
Eclipse OpenJ9 0.16

**Applies to the following JDK versions:**
All JDK versions

**Applies to the following platforms:**
All platforms

**For new command line options:**

- **Option name and syntax:** -XX:[+/-]ShareAnonymousClasses
- **Purpose:** Provides the ability to enable and disable storing and finding VM anonymous classes in the shared class cache

**Comment by doveye** [comment]
Hi @sogutbera, I have some questions for the doc :)

Currently, there's no mention of anonymous classes in the shared classes cache doc, so it's not clear what the new capability is. Is it ...
1. The ability to add anonymous classes to the shared cache - previously they were always excluded
or
2. The ability to exclude anonymous classes from the shared cache - previously they were always included?

In https://www.ibm.com/support/knowledgecenter/SSYKE2_8.0.0/com.ibm.java.vm.80.doc/docs/shrc_intro.html (some doc has yet to be moved from the old system to the OpenJ9 doc set), we say

> A shared cache can contain:
> - Bootstrap classes
> - Application classes
> - Metadata that describes the classes
> - Ahead-of-time (AOT) compiled code
> - Java byte arrays

Where do anonymous classes fit in this list - are they a type of existing class (eg bootstrap or application class), or should we add another list entry for them? (Forgive my Java ignorance!)

Is there a particular benefit of this new capability that we can mention in the What's New section? (Something besides just saying "you can now do this" - why would a user want to do this?)

Is there any other doc in https://www.eclipse.org/openj9/docs/xshareclasses/, https://www.eclipse.org/openj9/docs/shrc/, or the https://www.ibm.com/support/knowledgecenter/SSYKE2_8.0.0/com.ibm.java.vm.80.doc/docs/shrc.html section (you can see the section if you enable the table of contents) that needs updating? (For example, the behaviour of checkURLTimestamps is different for bootstrap classes compared to application classes.)

**Comment by sogutbera** [comment]
Hi @doveye, previously they were always excluded, now they are included by default but we also added the option to exclude them. 

Anonymous classes are either bootstrap classes or application classes so there is no need to add another list entry. 

The benefit is that the methods in the anonymous classes are now in the shared class cache so they can be aot'd which could improve startup performance.

This option is related to shared class but it's not a sub option. None of those docs need updating. Thank you.

**Comment by sogutbera** [comment]
@DanHeidinga can you take a look at this? Thanks.

**Comment by DanHeidinga** [comment]
I've updated the description to clarify that anonymous classes are classes loaded by Unsafe.defineAnonymousClass and are a VM construct.  These are different than the Java language version of anonymous classes.  (Confusing, I know, but that's the existing nomenclature)

**Comment by hangshao0** [comment]
Do we need to mention that we are currently storing/finding only Lambda-related classes from Unsafe.defineAnonymousClass() ? We may change this behavior in the future through.

**Comment by DanHeidinga** [comment]
> Do we need to mention that we are currently storing/finding only Lambda-related classes from Unsafe.defineAnonymousClass() ? We may change this behavior in the future though.

I've added a mention of the current behaviour and that it may be expanded in the future to #337

**Comment by pmhayward** [comment]
This issue now closed via PR #337
