### ISSUE TITLE
Increment the shared cache generation number and change of shared cache file format

### ISSUE THREAD

**Issue by hangshao0** [eclipse/openj9-docs#345]
**Issue or pull request number:**
*https://github.com/eclipse/openj9/pull/6536
https://github.com/eclipse/openj9/issues/5480*

**Overview:**
1. We increment the shared cache generation number from 39 to 41. All existing shared caches with generation number 39 and lower can be removed by `-Xshareclasses:name=<cacheName>,destroy`.
2. The format of shared cache file is changed, we append layer number `Lxx` to the shared cache file (both persistent cache and non-persistent cache). e.g. The cache file name is changed from `C290M4F1A64P_Cache1_G39 `to `C290M4F1A64P_Cache1_G41L00`. 

**Release target:**
*Eclipse OpenJ9 0.16*

**Applies to the following JDK versions:**
*Java 8 and up*

**Applies to the following platforms:**
*All platforms*

**For new command line options:**
The default layer number is 0 and all the existing options work as usual for layer 0 shared cache. 

There are new command line options added (by https://github.com/eclipse/openj9/pull/6536) to create and destroy cache that has layer number > 0, but we don't expect users to use those new options now, because JIT and DDR support are not ready yet. So there is no need to document the new options for the time being. 

- Purpose:
Allow one JVM to startup multiple shared classes caches. (I think we don't need to mention this for the user now) 
- Restrictions:
N.A.

**Comment by pshipton** [comment]
We should mention the format of `-Xshareclasses:listAllCaches` is modified, to include a layer number. Although I don't see any explanation of this output or any example.

**Comment by doveye** [comment]
Re  

> The cache file name is changed from C290M4F1A64P_Cache1_G39 to C290M4F1A64P_Cache1_G41L00.

According to the docs (https://eclipse.github.io/openj9-docs-staging/335/xshareclasses/#name), the default shared cache name is "sharedcc_%u", where %u is the user name. This is quite different from what is listed above?

**Comment by doveye** [comment]
I downloaded a build of 0.15.1 to have a play. A default cache is called sharedcc_ESTHERDovey according to listAllCaches, but the file that appears in the filesystem is C290M4F1A64P_sharedcc_ESTHERDovey_G37. So I guess the name as the user sees it (and uses it, eg with printAllStats) is unchanged. So we don't really need to mention point 2. in the description?

**Comment by doveye** [comment]
@hangshao0  ok, thanks. I've added a section to the release notes: https://eclipse.github.io/openj9-docs-staging/347/version0.16/#changes-to-the-shared-classes-cache-generation-number, based on info from previous generation number updates. We haven't mentioned the actual generation number in the past, and it isn't part of the name as returned by listAllCaches, so I haven't mentioned it. I've added a mention of the new "layer" column in the listAllCaches output though.

Can you please have a look at the draft link and let me know if anything needs changing, thanks.

**Comment by doveye** [comment]
Great, thanks Hang. Closing this issue.
