### ISSUE TITLE
-Xshareclasses:listAllCaches shows (AIX, Linux, macOS, and z/OS only)

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9-docs#346]
https://www.eclipse.org/openj9/docs/xshareclasses/#listallcaches-cache-utility

The doc shows `(AIX, Linux, macOS, and z/OS only)`. Not sure why as it also works on Windows or any other supported platform. Windows has a somewhat different output format and perhaps this used to be documented separately.

**Comment by pshipton** [comment]
Note the other places (snapshot utilities) which use `(AIX, Linux, macOS, and z/OS only)` will eventually need to include ARM AArch64. A better approach may be to use "platforms other than Windows".

**Comment by doveye** [comment]
Thanks Peter. I've removed the redundant platform restriction statement, and turned `(AIX, Linux, macOS, and z/OS only)` into `(Not Windows)`.
