### ISSUE TITLE
Sweep docs for deprecated options and remove

### ISSUE THREAD

**Issue by SueChaplain** [eclipse/openj9-docs#35]
Doc source contributed by IBM has some old deprecation statements that relate to IBM support. Any deprecated options should be removed.

**Comment by SueChaplain** [comment]
We should probably collect a list of what we've removed as the info might still be required in the IBM SDK documentation. 

So far, removed: -Xgcpolicy:subpool

**Comment by SueChaplain** [comment]
Hi @DanHeidinga 

I while ago you pointed out that an IBM SDK deprecation statement had inadvertently slipped into the content that was contributed to Eclipse. I created this issue to sweep the docs for anything else. For the most part I think that the remaining statements apply to OpenJ9, but I can remove the content entirely where appropriate.

Please can you take a look through this short list and let me know of anything you want removed or amended? 

(1) JIT environment variables: https://www.eclipse.org/openj9/docs/env_var/#deprecated-jit-options
(2) New statement applies to OpenJ9 on StringBuffer and StringBuilder: https://www.eclipse.org/openj9/docs/version0.9/#changes-to-the-javalangstring-class
(3) -Xcomp: https://www.eclipse.org/openj9/docs/xcomp/
(4) -Xfastresolve: https://www.eclipse.org/openj9/docs/xfastresolve/
(5) -Xpartialcompactgc / -Xnopartialcompactgc in Balanced section: https://www.eclipse.org/openj9/docs/xgcpolicy/#balanced
(6) -Xgc:splitheap: https://www.eclipse.org/openj9/docs/xgcsplitheap/
(7) -Xlp: https://www.eclipse.org/openj9/docs/xlp/
(8) -Xdisclaimjitscratch: https://www.eclipse.org/openj9/docs/xxdisclaimjitscratch/
(9) -Xzero: https://www.eclipse.org/openj9/docs/xzero/

I've seen mention in an OpenJ9 issue of the need to have an OpenJ9 deprecation policy. I'm not sure if this discussion has concluded but I guess that deprecation statements should be made in the release notes.

**Comment by DanHeidinga** [comment]
Thanks @SueChaplain I've skimmed each of those pages and agree the statements in these pages apply to OpenJ9.  No changes required.

**Comment by SueChaplain** [comment]
Thanks @DanHeidinga, I'll close this issue.
