### ISSUE TITLE
Document new command line options: -XX:[+/-]ShareUnsafeClasses

### ISSUE THREAD

**Issue by sogutbera** [eclipse/openj9-docs#351]
**Issue or pull request number:**
https://github.com/eclipse/openj9/pull/7149

**Overview:**
Add new command line options -XX:[+/-]ShareUnsafeClasses, which allow to enable and disable storing and finding classes created through Unsafe.defineClass in the shared class cache. The default is enabled.

**Release target:**
Eclipse OpenJ9 Release 0.17 (Java 8, 11, 13) Oct refresh

**Applies to the following JDK versions:**
All JDK versions

**Applies to the following platforms:**
All platforms

**For new command line options:**

- **Option name and syntax:** -XX:[+/-]ShareUnsafeClasses
- **Purpose:** Provides the ability to enable and disable storing and finding Unsafe classes in the shared class cache

**Comment by doveye** [comment]
@sogutbera Does this really need documenting? I noticed that Dan said in https://github.com/eclipse/openj9/issues/4985#issuecomment-524956888 that these options are not intended for end users, who are the target audience of the doc. If this option is only for service and test, we shouldn't be documenting it in user doc. @DanHeidinga

**Comment by DanHeidinga** [comment]
Given we've documented the anonymousclass options, this should also be documented

**Comment by hangshao0** [comment]
I see https://github.com/eclipse/openj9/pull/6896 is tagged to Release 0.17 (Java 8, 11, 13) Oct refresh. @sogutbera , can you update the release target in the description here ?

**Comment by sogutbera** [comment]
With this change, the behaviour of the command line option -XX:+ShareAnonymousClasses has also changed. It used to allow only lambda classes to be shared and now it allows all VM anonymous classes to be shared.

**Comment by doveye** [comment]
@DanHeidinga Re https://github.com/eclipse/openj9-docs/issues/351#issuecomment-526637588, we can always take out the anonymousclass options doc! Unnecessary extra info creates clutter that makes it more difficult for users to find info that they are looking for.

**Comment by DanHeidinga** [comment]
I think it makes sense to document these options.  We're mentioning the improvements in the readmes / new & noteworthy so we should also provide details on how to control or disable them if there's an issue

**Comment by pmhayward** [comment]
@DanHeidinga ... Assume nothing here is required for imminent 0.16 release? E.g. are docs for [-XX:+ShareAnonymousClasses](https://eclipse.github.io/openj9-docs/xxshareanonymousclasses/) OK as they are, for now?
Can you add a "doc:externals" label to eclipse/openj9#6896 so we don't "lose" it!

**Comment by pshipton** [comment]
Added the label
