### ISSUE TITLE
MessageDigest is re-enabled

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9-docs#353]
**Issue or pull request number:**
https://github.com/ibmruntimes/openj9-openjdk-jdk13/pull/9

https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/324
https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/191
https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/129

**Overview:**
MessageDigest is re-enabled

**Release target:**
Eclipse OpenJ9 0.16.0

**Applies to the following JDK versions:**
Java 13 for 0.16 and all other versions for 0.17
Technically MessageDigest wasn't disabled for Java 13, which hasn't been released before 0.16, but the docs don't reflect this.

**Applies to the following platforms:**
All

**Comment by pshipton** [comment]
@keithc-ca @ashbm5

**Comment by doveye** [comment]
I've changed the Java8+ image on the disabled restriction to Java 8, Java 11, and Java 12, so that it doesn't apply to Java 13. See eg https://eclipse.github.io/openj9-docs/djdknativedigest/. When we have the download doc package for 0.16.0, we'll change the text again to remove the restriction entirely for 0.17.0.

**Comment by keithc-ca** [comment]
Native message digests are enabled by default for all Java versions: see the PRs referenced in the description above.

**Comment by pshipton** [comment]
@keithc-ca we are only shipping Java 13 in the 0.16 release, the other version get the change in 0.17 which ships in Oct.

**Comment by doveye** [comment]
I've removed the restriction note for 0.17.0, so now the docs say that digest is enabled by default, with no exceptions. I've also added a small section in the What's new for 0.17.0: https://eclipse.github.io/openj9-docs/version0.17/.

Will close this item. If anyone has anything to add,  please reopen.
