### ISSUE TITLE
-Xminf and -Xminf documentation should explicitly specify the range of input values

### ISSUE THREAD

**Issue by fjeremic** [eclipse/openj9-docs#356]
**Page containing the error:**
https://www.eclipse.org/openj9/docs/xminf/

**Describe the error and the update needed:**
According to [1] the value is 0.0 - 1.0 based, however the default value indicated in the table on the documentation page says 30 and 60, which seems to imply the value is 0 - 100 based. We should indicate explicitly that the values are 0.0 - 1.0 based and adjust the default value to be 0.3 and 0.6 respectively.

[1] https://github.com/eclipse/openj9/issues/7005#issuecomment-529137808

**Comment by pshipton** [comment]
@amicic
