### ISSUE TITLE
Add -Xshareclasses:noPersistentDiskSpaceCheck option

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9-docs#357]
**Issue or pull request number:**
https://github.com/eclipse/openj9/pull/7001

**Overview:**
Skips the disk space check done before creating/opening a persistent shared cache. Can be used with file systems which don't support checking free space. If there isn't enough disk space available when the JVM writes to the shared cache memory, a SIGBUG or SIGSEGV signal will occur and the JVM terminates. This behavior occurs regardless of using the `-Xshareclasses:noPersistentDiskSpaceCheck` option, but without the option the JVM checks if enough disk space is available in advance to help avoid it.

noPersistentDiskSpaceCheck is not required when running readOnly, as there is no disk space check in this case.

**Release target:**
Eclipse OpenJ9 0.17.0

**Applies to the following JDK versions:**
All

**Applies to the following platforms:**
All

**For new command line options:**

`-Xshareclasses:noPersistentDiskSpaceCheck`
- Purpose: see above
- Restrictions: see above

**Comment by SueChaplain** [comment]
@pshipton 

> This behavior occurs regardless of using the -Xshareclasses:noPersistentDiskSpaceCheck option, but without the option the JVM checks if enough disk space is available in advance to help avoid it.

The VM tries to avoid a signal and termination? How does it avoid this?

**Comment by pshipton** [comment]
@SueChaplain the VM doesn't avoid getting a signal and terminating. If you run out of disk space and then try to write to the shared cache, a signal will occur. The VM normally validates there is enough space when the cache is created, but the free disk space can change later. As long as the cache isn't read-only or full, there is a risk of getting a signal.

**Comment by SueChaplain** [comment]
Jenkins doc stage
