### ISSUE TITLE
New API in SharedClassCacheInfo.java and new field in jvmtiSharedCacheInfo

### ISSUE THREAD

**Issue by hangshao0** [eclipse/openj9-docs#358]
**Issue or pull request number:**
*https://github.com/eclipse/openj9/pull/7017/*

**Overview:**
*A new API: getCacheLayer() is added to SharedClassCacheInfo.java
 A new filed: `jint layer` is added to struct jvmtiSharedCacheInfo in ibmjvmti.h*

**Release target:**
Eclipse OpenJ9 0.18.0

**Applies to the following JDK versions:**
*All versions*

**Applies to the following platforms:**
*All platforms*

**For new command line options:** N.A.

- Option name and syntax: *e.g. -XX[+|-]NewOptionName*
N.A.

- Purpose: We changed the cache file name format to include the layer number (see https://github.com/eclipse/openj9-docs/issues/345). Now we are providing the cache layer information through JCL API and JVMTI struct. 
- Restrictions: N.A.

**Comment by SueChaplain** [comment]
@pshipton - looks like we haven't updated the JVMTI topic yet. Happy to do so - can you comment on where we are with command line options please.

**Comment by pshipton** [comment]
@SueChaplain the `createLayer` and related command line options are already documented.
