### ISSUE TITLE
Make note that recent builds from adoptopenjdk.net are CUDA-enabled

### ISSUE THREAD

**Issue by keithc-ca** [eclipse/openj9-docs#359]
**Subject:**
*CUDA is now enabled on supported platforms in builds from AdoptOpenJDK*

Nightly Linux builds for for x64 and ppc64le were CUDA-enabled beginning about Aug. 25; Windows builds for x64 followed suit around Sept. 3. This applies to all versions of OpenJ9 being built at AdoptOpenJDK; upcoming release builds should also have this feature.

**Comment by pshipton** [comment]
I assume this applies to the 0.16 release Java 13 builds.

**Comment by keithc-ca** [comment]
> I assume this applies to the 0.16 release Java 13 builds.

Yes, I expect so.

**Comment by SueChaplain** [comment]
@keithc-ca - if users expect to use CUDA do they also need to download something from somewhere? If so, we can add this to the **https://www.eclipse.org/openj9/docs/adoptopenjdk/** topic, pre-req section.

**Comment by keithc-ca** [comment]
A user that might benefit from CUDA-enabled VMs isn't likely to have to do anything extra.

If they have the hardware and have installed the GPU driver from NVIDIA, they should have the necessary shared libraries.
