### ISSUE TITLE
Document new command line options: -XX:[+|-]ClassRelationshipVerifier

### ISSUE THREAD

**Issue by sharon-wang** [eclipse/openj9-docs#360]
**Issue or pull request number:**
https://github.com/eclipse/openj9/pull/7089

**Overview:**
Add a new command line option `-XX:[+|-]ClassRelationshipVerifier`, which allows users to enable/disable recording and validating class relationships in the verifier.

**Release target:**
Eclipse OpenJ9 0.17.0

**Applies to the following JDK versions:**
All JDK versions.

**Applies to the following platforms:**
All platforms.

**For new command line options:**

- **Option name and syntax:** `-XX[+|-]ClassRelationshipVerifier`
- **Purpose:** To avoid unnecessary class loads, which reduces VM startup time.
- **Restrictions:** Cannot be used with `-Xfuture`. Note that `-Xverify:all` also enables `-Xfuture`.

**Comment by DanHeidinga** [comment]
The `-XX:[+|-]ClassRelationshipVerifier` is a new approach to bytecode verification that delays validating the relationships between classes until the classes would have been naturally loaded by the programs execution.

It operates by recording the relationships asserted by the bytecode when doing the linear StackMapTable-based verification and preventing classes that violate those relationships from being loaded.

This moves class loading to where it would occur during execution and, if the classes are not needed by this execution, they are never loaded.
