### ISSUE TITLE
HOOKS section behavior change in javadump

### ISSUE THREAD

**Issue by LinHu2016** [eclipse/openj9-docs#364]
**Issue or pull request number:**
PR https://github.com/eclipse/omr/pull/4221 (https://github.com/eclipse/openj9/pull/6822) has changed current behavior in javadump, need to update documentation to reflect the change.

**Overview:**
Base on the service team requests, a few of enhancements have been done in HOOKS section of javadump.
1, Changing the duration time from millisecond to microsecond for increased precision
2, new field 3HKTOTALTIME for the sum of previous events duration 
3, reset the hook statistics after each java dump (need to mention "statistics data only represent the period since the previous javacore" in document).

**Release target:**
0.17

**Applies to the following JDK versions:**
Java 8 and later 

**Applies to the following platforms:**
All platforms

**sample**
NULL           ------------------------------------------------------------------------
0SECTION       HOOK subcomponent dump routine
NULL           ==============================
1NOTE          These data are reset every time a javacore is taken
1HKINTERFACE   MM_OMRHookInterface
NULL           ------------------------------------------------------------------------
1HKINTERFACE MM_OMRHookInterface
NULL           ------------------------------------------------------------------------
1HKINTERFACE   MM_PrivateHookInterface
NULL           ------------------------------------------------------------------------
1HKINTERFACE MM_HookInterface
NULL           ------------------------------------------------------------------------
1HKINTERFACE J9VMHookInterface
NULL           ------------------------------------------------------------------------
2HKEVENTID     1
3HKCALLCOUNT       1687
3HKTOTALTIME       418576us
3HKLAST            Last Callback
4HKCALLSITE           trcengine.c:395
4HKSTARTTIME          Start Time: 2019-10-03T12:28:32.618
4HKDURATION           Duration  : 190us
3HKLONGST          Longest Callback
4HKCALLSITE           trcengine.c:395
4HKSTARTTIME          Start Time: 2019-10-03T12:25:20.735
4HKDURATION           Duration  : 128611us
NULL
...
1HKINTERFACE   J9VMZipCachePoolHookInterface
NULL           ------------------------------------------------------------------------
1HKINTERFACE   J9JITHookInterface
NULL           ------------------------------------------------------------------------
2HKEVENTID     3
3HKCALLCOUNT       2440
3HKTOTALTIME       4160us
3HKLAST            Last Callback
4HKCALLSITE           common/mgmtinit.c:193
4HKSTARTTIME          Start Time: 2019-10-03T12:28:54.504
4HKDURATION           Duration  : 1us
3HKLONGST          Longest Callback
4HKCALLSITE           common/mgmtinit.c:193
4HKSTARTTIME          Start Time: 2019-10-03T12:26:38.834
4HKDURATION           Duration  : 13us
NULL
...

**Comment by pshipton** [comment]
@LinHu2016 note the OMR change is merged so it will be in the OpenJ9 0.17 release, I expect the OpenJ9 portion needs to be this release as well, for with the code split is Sunday Sep 22. Otherwise it can be double delivered into the 0.17 branch once it has been created.

**Comment by pshipton** [comment]
@amicic

**Comment by pshipton** [comment]
The changes for this are delivered in 0.17

**Comment by pmhayward** [comment]
@LinHu2016 , @pshipton ... please review doc changes at 
https://eclipse.github.io/openj9-docs-staging/384/version0.17/#the-format-of-the-hooks-section-of-a-java-dump-has-changed
and follow link to review changes in Java dump topic. 

In particular, I note that the date format in the example has changed from previously, e.g.:
2018-08-30T21:55:47.601 to 5168-03-05T00:15:14.664
Is this OK? (The original examples in this topic were all taken from the same Java dump; does it matter that this section is now from a different one? Should the dates/times be left as they were in order to match?)

Just a picky thing!... in the new output, there's a message: "These data are reset..." It's usual practice to treat "data" as a singular noun, even though it's the plural of "datum". Thus: "This data is reset..." (See, for example, IBM Word Usage.) The docs will, of course, continue to reflect the actual output, but it would be good to see that fixed!

Thanks

**Comment by pshipton** [comment]
> It's usual practice to treat "data" as a singular noun, even though it's the plural of "datum"

@keithc-ca see previous comment. Feel like fixing it?

**Comment by pshipton** [comment]
Re the date format, using the year 5168 seems very weird. I suggest changing the date to reflect reality, like 2019-10-03. Using the original date would be wrong because output from 2018 would be in the old format.

**Comment by keithc-ca** [comment]
I assume 'IBM Word Usage' refers to [1]. I was being nitpicky suggesting grammar that was consistent with 'data' being plural, but perhaps consistency (with common usage) is more important: I will create a PR to adjust that.

[1] https://www.ibm.com/developerworks/library/styleguidelines/index.html

**Comment by LinHu2016** [comment]
> @LinHu2016 , @pshipton ... please review doc changes at
> https://eclipse.github.io/openj9-docs-staging/384/version0.17/#the-format-of-the-hooks-section-of-a-java-dump-has-changed
> and follow link to review changes in Java dump topic.
> 
> In particular, I note that the date format in the example has changed from previously, e.g.:
> 2018-08-30T21:55:47.601
> to
> 5168-03-05T00:15:14.664
> Is this OK? (The original examples in this topic were all taken from the same Java dump; does it matter that this section is now from a different one? Should the dates/times be left as they were in order to match?)
> 
> Just a picky thing!... in the new output, there's a message: "These data are reset..." It's usual practice to treat "data" as a singular noun, even though it's the plural of "datum". Thus: "This data is reset..." (See, for example, IBM Word Usage.) The docs will, of course, continue to reflect the actual output, but it would be good to see that fixed!
> 
> Thanks
Thanks @pmhayward point out 4HKSTARTTIME Start Time issue, it is actually bug in javadump code due to timestamp precision change(from ms to us), I will try to create a patch in openj9 for release 0.17 and update the sample later.

**Comment by keithc-ca** [comment]
I'll also try to fix the problem with the dates.

**Comment by LinHu2016** [comment]
**new sample**

NULL           ------------------------------------------------------------------------
0SECTION       HOOK subcomponent dump routine
NULL           ==============================
1NOTE          These data are reset every time a javacore is taken
1HKINTERFACE   MM_OMRHookInterface
NULL           ------------------------------------------------------------------------
1HKINTERFACE MM_OMRHookInterface
NULL           ------------------------------------------------------------------------
1HKINTERFACE   MM_PrivateHookInterface
NULL           ------------------------------------------------------------------------
1HKINTERFACE MM_HookInterface
NULL           ------------------------------------------------------------------------
1HKINTERFACE J9VMHookInterface
NULL           ------------------------------------------------------------------------
2HKEVENTID     1
3HKCALLCOUNT       1687
3HKTOTALTIME       418576us
3HKLAST            Last Callback
4HKCALLSITE           trcengine.c:395
4HKSTARTTIME          Start Time: 2019-10-03T12:28:32.618
4HKDURATION           Duration  : 190us
3HKLONGST          Longest Callback
4HKCALLSITE           trcengine.c:395
4HKSTARTTIME          Start Time: 2019-10-03T12:25:20.735
4HKDURATION           Duration  : 128611us
NULL
...
1HKINTERFACE   J9VMZipCachePoolHookInterface
NULL           ------------------------------------------------------------------------
1HKINTERFACE   J9JITHookInterface
NULL           ------------------------------------------------------------------------
2HKEVENTID     3
3HKCALLCOUNT       2440
3HKTOTALTIME       4160us
3HKLAST            Last Callback
4HKCALLSITE           common/mgmtinit.c:193
4HKSTARTTIME          Start Time: 2019-10-03T12:28:54.504
4HKDURATION           Duration  : 1us
3HKLONGST          Longest Callback
4HKCALLSITE           common/mgmtinit.c:193
4HKSTARTTIME          Start Time: 2019-10-03T12:26:38.834
4HKDURATION           Duration  : 13us
NULL
...

**Comment by keithc-ca** [comment]
https://github.com/eclipse/openj9/pull/7341, if merged, will adjust the presentation a little.

**Comment by SueChaplain** [comment]
Reopening issue. @pmhayward -FYI
