### ISSUE TITLE
Link to the support statement from the website

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9-docs#38]
The support statement (https://www.eclipse.org/openj9/docs/openj9_support/index.html) is currently hard to find from the website.

Can we have this linked from the main page?

**Comment by SueChaplain** [comment]
I agree it's hard to find and had planned to put something into the intro topic that will take people straight there. We'll also update the website (when Eclipse fix our [bug](https://bugs.eclipse.org/bugs/show_bug.cgi?id=535677)) ... I was wanting to do this in line with the 0.9.0 release. The main page is getting somewhat cluttered though (as pointed out in the design critique) ... we'll work on finding a way to get this in nicely.

**Comment by SueChaplain** [comment]
@DanHeidinga 

The website now has an FAQ for OpenJ9 support, which links to the full support page.
I also have a PR waiting to land that adds a support section into the Introduction topic, which provides a link to the full support page.

Are you ok with this issue being closed please?

**Comment by DanHeidinga** [comment]
Can the supported environments page be linked from the hamburger menu in the top left?  I think it's important enough that it should be easy to find.  It took me longer than I'd like to admit to find it in the FAQ

**Comment by SueChaplain** [comment]
Hmm ..... ok, let me think through this one. I was a little unsure about bolting external sites into the hamburger menu, but did do that for the blog to avoid making the landing page any busier than it already is (remember the design review feedback?). Adding another external link, which also has a very long name,  might not be the right thing to do.

Peter is suggesting a  "box" on the landing page, that has some key resources listed in there and moving the blog there too.  Maybe there is some mileage in this.

I do understand the problem .... leave it with us to think about some options.

**Comment by SueChaplain** [comment]
Issue clean up. The website redesign did not cater for linking to the support statement and this did not come up in the design requirements. Since this was raised, we did put something in the first topic of the user docs to connect people to the supported env topic, so I think this issue has been resolved in a different way. Closing
