### ISSUE TITLE
Default change of -Dcom.ibm.enableClassCaching=[true|false]

### ISSUE THREAD

**Issue by theresa-m** [eclipse/openj9-docs#386]
**Issue or pull request number:**
https://github.com/eclipse/openj9/issues/7332

**Overview:**
Default value of `-Dcom.ibm.enableClassCaching=[true|false]` has been changed from true to false, disabling LUDCL by default.

**Release target:**
Eclipse OpenJ9 0.17.0

**Applies to the following JDK versions:**
8,11,13,next (not IBM)

**Applies to the following platforms:**
All platforms

**Comment by DanHeidinga** [comment]
FYI @SueChaplain - this will affect the 0.17 release

**Comment by SueChaplain** [comment]
@theresa-m @DanHeidinga - the docs already have this option as disabled by default. If changes were made to enable it by default, this was not reflected in the docs.

Please confirm the change required.

**Comment by DanHeidinga** [comment]
The docs and the VM's behaviour weren't consistent - the docs said disabled while the VM actually enabled it. 

We're looking for a release note to indicate the change in behaviour.

Note, this change was made to the `0.17.0` release

**Comment by pshipton** [comment]
Reopening until we have a release note to mention the change in behavior.

**Comment by pshipton** [comment]
The release note should mention there are cases where enabling `-Dcom.ibm.enableClassCaching` does not work. i.e. https://github.com/eclipse/openj9/issues/7332

**Comment by SueChaplain** [comment]
I'll modify what I put in there tomorrow: https://github.com/eclipse/openj9/blob/0bf1c65719e82ecb004053979b2c94d668ea3663/doc/release-notes/0.17/0.17.md

**Comment by SueChaplain** [comment]
@pshipton - are you happy for this to be closed now please?

**Comment by pshipton** [comment]
No, I think more clarity is needed in https://eclipse.github.io/openj9-docs/version0.17/#ludcl-caching-disabled-by-default, which doesn't explain why it's been disabled or what problems could occur if re-enabled. This is the content I see now.
```
By caching the Latest User Defined Class Loader (LUDCL), Java applications that use deserialization extensively can see a performance improvement. This capability is controlled by the -Dcom.ibm.enableClassCaching system property and is now disabled by default. Versions of the documentation before 0.17.0 incorrectly identified this property as disabled by default when it was actually enabled by default in the VM.
```
