### ISSUE TITLE
-Xmso has 1MB minimum size on z/OS 64-bit

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9-docs#396]
**Issue or pull request number:**
https://github.com/eclipse/openj9/pull/7304

**Overview:**
Even when the user requests a smaller size, the minimum -Xmso is set to 1MB since this is the size allocated by the /OS.

**Release target:**
Eclipse OpenJ9 0.18.0

**Applies to the following JDK versions:**
All

**Applies to the following platforms:**
z/OS (64-bit only)

**Comment by SueChaplain** [comment]
Suggested changes:

- update the xmso topic **Default settings** section to indicate that setting a value less than the default on 64-bit z/OS (1MB) is ignored by the VM for the reasons you state.
- update the version0.18.md topic to add a section for this behaviour change, with a short reason and link to the xmso.md topic. Ensure that a link to the section is added at the top of the topic.

Question: Does this mean that `-Xiss` should be 1MB for 64-bit z/OS too?  In default settings it is 2KB.

**Comment by pshipton** [comment]
> Does this mean that -Xiss should be 1MB for 64-bit z/OS too? In default settings it is 2KB.

-Xiss controls the java stack size, while -Xmso controls the native stack size.
