### ISSUE TITLE
Update supported environments to indicate gcc 4.4.7 and gcc 4.8.5

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9-docs#40]
https://www.eclipse.org/openj9/docs/openj9_support/index.html indicates gcc 4.8.4 is the minimum gcc level for Java 8, however we need to indicate gcc 4.4 is the minimum level supported. 4.4.7 is the level installed on Ubuntu 14 so we can indicate that version.

We don't want to support 4.4 forever, so please indicate that we plan to update the minimum level to at least 4.8 in the future.

I also notice Java 9/10 indicate gcc 4.8.4 but please change Java 9 and later to be 4.8.5 as this is the level you get when gcc-4.8 is installed on Ubuntu 16.

**Comment by SueChaplain** [comment]
Addressing this by amending https://github.com/eclipse/openj9-docs/pull/32, which is open and being reviewed by Dan for adding Win32 in to the Java 8 table. Plse review the changes there.
