### ISSUE TITLE
Education for developers making doc contributions

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9-docs#408]
[openj9-doc-contibutions.pptx](https://github.com/eclipse/openj9-docs/files/3763294/openj9-doc-contibutions.pptx)

Video presentation 
[Contributing to OpenJ9 docs.zip](https://github.com/eclipse/openj9-docs/files/3763484/Contributing.to.OpenJ9.docs.zip)

**Comment by SueChaplain** [comment]
We should add something to the CONTRIBUTING.md that points to these files in the repo. No obvious folder for them at the moment, so suggest maybe a `process` folder but open to suggestions @pmhayward?

**Comment by SueChaplain** [comment]
Files stored here: https://github.com/eclipse/openj9-docs/tree/master/process
Contribution guidelines updated
