### ISSUE TITLE
Mobile hamburger menu not working 

### ISSUE THREAD

**Issue by SueChaplain** [eclipse/openj9-docs#420]
See https://github.com/eclipse/openj9-website/issues/199, which was raised against the website. The issue exists here in the docs repo.

**Comment by SueChaplain** [comment]
This issue has been fixed.

**Comment by AdamBrousseau** [comment]
Can confirm this works now on my device [1]. Thanks @SueChaplain and @Bazif-Khan .
The only thing I still notice is the menu seems to be cut off slightly (minor) [2] and the OpenJ9 logo appears to be the same colour as the background so I can only see "J9" [1].
[1]
![Screenshot_20191106-115917__01](https://user-images.githubusercontent.com/6430052/68327666-c4359c00-009b-11ea-9327-3e151ab34c29.jpg)
[2]
![Screenshot_20191106-115912__01](https://user-images.githubusercontent.com/6430052/68327665-c4359c00-009b-11ea-9057-f7176d2f3651.jpg)

**Comment by SueChaplain** [comment]
@AdamBrousseau - yes, I agree there is still some work to do. Main focus here was to get the menu working asap and fix appearances later. Please can you open a new issue so that we don't lose this work. Thanks!
