### ISSUE TITLE
Docs Website TOC on mobile loses OpenJ9 logo into background colour

### ISSUE THREAD

**Issue by AdamBrousseau** [eclipse/openj9-docs#426]
**Subject:**
Extracted from https://github.com/eclipse/openj9-docs/issues/420#issuecomment-550448025
OpenJ9 logo colour matches the background colour. Only the white "J9" is visible.
![Screenshot_20191106-115917__01](https://user-images.githubusercontent.com/6430052/68329159-b2092d00-009e-11ea-9e34-8e41621dad89.jpg)

**Suggestion:**

**Comment by SueChaplain** [comment]
Issue closed by https://github.com/eclipse/openj9-docs/pull/428 ..... addresses draft docs. Change will be in release docs for 0.18.0.
