### ISSUE TITLE
JVM -XcompilationThreads option documentation incorrect?

### ISSUE THREAD

**Issue by PascalSchumacher** [eclipse/openj9-docs#435]
**Page containing the error:**

https://www.eclipse.org/openj9/docs/xcompilationthreads

**Describe the error and the update needed:**

```
-XcompilationThreads<n>

where <n> is the number of threads, in the range 1-4 inclusive. A number greater than 4 prevents the Java™ VM from starting successfully. 
```

Seems incorrect, because `-XcompilationThreads7` works.

If `-XcompilationThreads<n>` is not specified, I see seven compilation threads (`JIT Compilation Thread-0`... `JIT Compilation Thread-6`). So `-XcompilationThreads7` seems to be the default (at least on my machine).

Or am I miss understanding something?

I am using:
```
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.17.0, JRE 11 Windows 10 amd64-64-Bit 20191031_114 (JIT enabled, AOT enabled)
OpenJ9   - 77c1cf708
OMR      - 20db4fbc
JCL      - 775c5eb03a based on jdk-11.0.5+10)
```

Thank you very much for providing OpenJ9!

**Comment by DanHeidinga** [comment]
Looking at the code, it seems the limit should be less than 8:

**Comment by mpirvu** [comment]
Indeed, the maximum number of compilation threads has been increased to 7. There is an additional compilation thread (called the JIT Diagnostic) that kicks-in in case of a crash, but that doesn't count from a user's perspective. The documetation need to be updated.

**Comment by pshipton** [comment]
@mpirvu as developers are supposed to create PRs for doc changes now, can you please create the PR to fix the limit.
