### ISSUE TITLE
Add support for Hotspot GC options

### ISSUE THREAD

**Issue by AlenBadel** [eclipse/openj9-docs#453]
See associated OpenJ9 PR
https://github.com/eclipse/openj9/pull/7723

**Overview:**
To mitigate the effort required for users to migrate to OpenJ9 from Hotspot the following option mappings have been made. 

**-XX:ParallelCMSThreads=N** to **-XconcurrentbackgroundN**
**-XX:ConcGCThreads=N** to **-XconcurrentbackgroundN**
**-XX:ParallelGCThreads=N** to **-XgcthreadsN**

**Release target:**
Eclipse OpenJ9 0.18.0

**Applies to the following JDK versions:**
8 and later

**Applies to the following platforms:**
All platforms

**For new command line options:**

**-XX:ParallelCMSThreads=N** and
**-XX:ConcGCThreads=N**
(See https://www.eclipse.org/openj9/docs/xconcurrentbackground)

**-XX:ParallelGCThreads=N**
(See https://www.eclipse.org/openj9/docs/xgcthreads)

**Comment by AlenBadel** [comment]
If there is any further clarification requested on the new command line options please let me know.

**Comment by SueChaplain** [comment]
Hi @AlenBadel - this all seems quite straightforward. In addition to the new topics for the -XX options, an update will be needed to the [Switching to OpenJ9](https://www.eclipse.org/openj9/docs/cmdline_migration/) topic to add them to the table, along with their equivalent OpenJ9 commands.

We'll also need one new section in the release topic, which can talk about the improvements in compatibility with HotSpot, similar to content that's been written before. For example, https://www.eclipse.org/openj9/docs/version0.11/#support-for-openjdk-hotspot-options

If you need any help with these changes, please reach out.

**Comment by SueChaplain** [comment]
Closed by https://github.com/eclipse/openj9-docs/pull/464
