### ISSUE TITLE
 [doc:externals] French translation of the readme.md file 

### ISSUE THREAD

**Issue by Yas01** [eclipse/openj9-docs#454]
**Issue or pull request number:**

*https://github.com/eclipse/openj9/pull/8016*
*https://github.com/Yas01/openj9/pull/1*

**Overview:**
*Proposal of a french translation of the README.md file. This translation can be accessed by a link in the original file to a new file named README.fr.md.*

**Release target:**
*E.g. Eclipse OpenJ9 0.17.0*

**Applies to the following JDK versions:**
*8 and later*

**Applies to the following platforms:**
*E.g. All platforms*

**Comment by pshipton** [comment]
We don't need this docs Issue in order to accept the French REAME in the OpenJ9 project, so I'll just close it. The Issues in this repo describe changes to the User Guide.

**Comment by Yas01** [comment]
Alright. So, how can I proceed If I want to suggest a French documentation in the OpenJ9 project?

**Comment by pshipton** [comment]
@Yas01 you can proceed to fix the things mentioned in https://github.com/eclipse/openj9/pull/8018
