### ISSUE TITLE
Change to default shared cache size

### ISSUE THREAD

**Issue by hangshao0** [eclipse/openj9-docs#46]
**Issue or pull request number:**
*Issue number :  https://github.com/eclipse/openj9/issues/1164 and https://github.com/eclipse/openj9/issues/2174, Pull Request number: https://github.com/eclipse/openj9/issues/1930 and https://github.com/eclipse/openj9/pull/2195*

**Overview:**
The default shared cache size will be used if user does not specify "-Xscmx" or "-XX:SharedCacheHardLimit=" in the command line when creating a new shared cache. The default shared cache size is changed to 300MB with a softmax size of 64MB on 64-bit platforms on Java 9 and up, with the following 2 exceptions:
1. For persistent cache, if the free disk space is < 6GB, we will set the default cache size to 64MB with no softmax size.
2. For non-persistent cache, the cache size is limited by SHMMAX. If SHMMAX < 300MB, the default shared cache size will be set to SHMMAX. There will be a softmx setting of 64MB if the default cache size (which is SHMMAX in this case) > 80MB. Otherwise, we won't set softmx.

**Applies to the following JDK versions:**
*9 and later*

**Applies to the following platforms:**
*All 64-bit platforms*

**For new command line options:**
N.A.

**Comment by SueChaplain** [comment]
Queried which OpenJ9 release this targets. Issue and PR not marked.

**Comment by hangshao0** [comment]
It should be v0.9.0

**Comment by SueChaplain** [comment]
I've been basing 0.9.0 content on items that target the 0.9.0 milestone: https://github.com/eclipse/openj9/milestone/2?closed=1

This wasn't in it, so has missed the what's new and release notes. Please confirm where it landed and we'll have to retrospectively update the OpenJ9 user docs, OpenJ9 release notes and downstream documentation (IBM).

**Comment by hangshao0** [comment]
> Please confirm where it landed and we'll have to retrospectively update the OpenJ9 user docs, OpenJ9 release notes and downstream documentation (IBM). 

This change is in OpenJ9 v0.9.0. This change applies to Java 9 and up. But I think IBM SDK does not have a Java 9+ release yet.

**Comment by SueChaplain** [comment]
@hangshao0 
Trying to figure out how to add this in to the docs. So question for clarity ....

... if you run -Xshareclasses without any suboptions, do you get a  persistent shared cache of 300MB with a softmax setting of 64MB? [Java SE 9 and later>] If there is less than 6GB of free disk space, the size is set to  64MB.[<]

If so I can put it up front in the -Xshareclasses topic: https://www.eclipse.org/openj9/docs/xshareclasses/

z/OS you can only have a non-persistent cache, so I could add a caveat here but probably not needed as it is covered by the persistent and nonpersistent options further in the topic.

**Comment by hangshao0** [comment]
@SueChaplain 

I have updated the description so that things become more clear and accurate. Hope it answers your question.

**Comment by SueChaplain** [comment]
Thanks @hangshao0 

A couple more questions:

- You have used the term softmax and softmx in your description. I'm assuming you mean the soft maximum size of the cache (`-xscmx`) and not (`-xsoftmx`) where mentioned.
- `SHMMAX` is Linux. If users are on Win64, is there an equivalent setting that we should mention? AIX64? z/OS64?

**Comment by hangshao0** [comment]
> You have used the term softmax and softmx in your description. I'm assuming you mean the soft maximum size of the cache (-xscmx) and not (-xsoftmx) where mentioned.

Yes, I mean soft maximum size of the cache (-Xscmx).

> SHMMAX is Linux. If users are on Win64, is there an equivalent setting that we should mention? AIX64? z/OS64?

No. For non-persistent cache, this change only checks SHMMAX. If there is no SHMMAX or SHMMAX >= 300MB, we will go on setting the default shared cache size to 300MB (with a shared cache soft maximum size of 64MB).
