### ISSUE TITLE
java -Xrunhprof    How To collect the profiling data during execution

### ISSUE THREAD

**Issue by XinXianChen** [eclipse/openj9-docs#465]
How To collect the profiling data during execution

**Comment by SueChaplain** [comment]
Hi @XinXianChen - Please can you provide a little more information about your issue? Is this an option you would like to see supported by the OpenJ9 VM?

**Comment by XinXianChen** [comment]
> 嗨@XinXianChen -请你能提供有关您的问题多一点信息？您是否希望OpenJ9 VM支持该选项？

I want to get a memory dump file (hprof format) during program running

**Comment by pshipton** [comment]
There are some instruction here https://docs.oracle.com/javase/8/docs/technotes/samples/hprof.html

**Comment by SueChaplain** [comment]
Closing this query as Peter has provided some instructions.
