### ISSUE TITLE
Validate what OpenJ9 does for the -Xverify option

### ISSUE THREAD

**Issue by SueChaplain** [eclipse/openj9-docs#47]
**Page containing the error:**

https://www.eclipse.org/openj9/docs/xverify/

**Describe the error and the update needed:**

Default shows as `all`, which based on recent conversations doesn't sound correct if maximum verification would have an effect on performance. 
Is `remote` the default, as with HotSpot? What exactly does OpenJ9 verify? All classes that are not loaded by the bootstrap class loader - i.e. everything apart from system classes?

**Comment by pshipton** [comment]
Reading the code, the default verification doesn't include bootstrap classes, and doesn't enable -Xfuture verification. All non-bootstrap classes are verified.

-Xverify:all adds bootstrap class verification, and enables -Xfuture verification.

**Comment by SueChaplain** [comment]
So:

-Xverify on its own: All non-bootstrap classes are verified
-Xverify:all: Adds bootstrap class verification, and enables -Xfuture verification.
-Xverify:remote has the same effect as `all`

Hotspot implementation is slightly different, so just double checking.

**Comment by DanHeidinga** [comment]
`-Xverify:remote` == `-Xverify`

We don't differentiate between remote and local classes, apart from trusting the bootclasspath

**Comment by pmhayward** [comment]
PR #50 merged
