### ISSUE TITLE
Platform and compiler changes for 0.19.0

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9-docs#537]
**Subject:**
https://eclipse.github.io/openj9-docs/version0.19

I noticed the following section in the What's New for the 0.19 release. I've added some comments inline.

**Platform and compiler changes**
For all supported versions of OpenJDK, there have been some minor changes to OpenJ9 that you might want to be aware of:

Linux x86 64-bit and Linux on POWER® LE 64-bit have moved to the gcc 7.5 compiler.
- zlinux also moved

Linux on IBM Z® 64-bit compilation has moved to RHEL 7.
- this only occurred for builds at the OpenJ9 project, used for test at the OpenJ9 project. Builds at AdoptOpenJDK were already at RHEL 7.

Windows Server 2019 is now a supported platform.
- it was always supported, we had just forgotten to list it

**Comment by pmhayward** [comment]
Will include zLinux with other Linuxs.
Will remove other items from What's new as they're not really new!
