### ISSUE TITLE
Jcmd dump with default settings

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9-docs#538]
**Issue or pull request number:**
https://github.com/eclipse/openj9/pull/8744

**Overview:**
Previously using `jcmd` with `Dump.java` (or `Dump.snap` and `Dump.system`) without a filename gives an error and its help shows that a file name is required.
Now `jcmd` support `Dump` without a file name,  the default settings like `-Xdump` is applied instead.

**Release target:**
*Eclipse OpenJ9 0.20.0*

**Applies to the following JDK versions:**
*JDK 8 +*

**Applies to the following platforms:**
*All platforms*

fyi @pshipton

**Comment by SueChaplain** [comment]
@JasonFengJ9 - are we expecting a PR for this one for 0.20.0 please?

**Comment by JasonFengJ9** [comment]
@SueChaplain yes, will open a PR for 0.20.0 release.
