### ISSUE TITLE
Inclusion of AArch64

### ISSUE THREAD

**Issue by pmhayward** [eclipse/openj9-docs#547]
AArch64 needs to be mentioned in "What's new" for 0.20.0 as "early access build."

**Comment by pmhayward** [comment]
@pshipton ... Can you provide some words that I can add to the OpenJ9 docs "What's new" (if that's the right place for it be), please?
"AArch64" - is that the right spelling / capitalization? Is it the same as, or related to ARM64? (Excuse ignorance!)

**Comment by SueChaplain** [comment]
@pshipton - do we also need to update the supported environments topic

**Comment by pshipton** [comment]
> Can you provide some words [for AArch64]

I'll defer to @0xdaryl and/or @knn-k 

> do we also need to update the supported environments topic

Yes we do, although it should indicate the platform is early access and has a list of known problems/limitations.

**Comment by SueChaplain** [comment]
> Yes we do, although it should indicate the platform is early access and has a list of known problems/limitations.

Are those already documented somewhere or should we add them to the release notes?

**Comment by pshipton** [comment]
Daryl and Konno-san will have to provide the list. There is still fixing going on so I expect the final don't be finalized until closer to the GA.
