### ISSUE TITLE
Hotspot / OpenJ9 commands comparison topic

### ISSUE THREAD

**Issue by SueChaplain** [eclipse/openj9-docs#55]
**New topic**

For OpenJDK developers and users that are familiar with HotSpot options, we should carry a topic that helps people find the equivalent command in OpenJ9.

| HotSpot Option | OpenJ9 Option | Usage |
|:------------------|:-------------------|:-------|
| `-Xgc`                 | `-Xgcpolicy`        | Configuring your garbage collection policy |
| `-XX:ParallelGCThreads=<N>` |  `-Xgcthreads` | Configure number of GC threads |
| `-XX:+-UseNUMA` | `-Xnuma` | appear similar - investigation needed |
| `-XX:+DisableExplicitGC` | `-Xdisableexplicitgc` | Disables System.gc() calls |
| `-XX:-DisableExplicitGC` | `-Xenableexplicitgc` | Reenables System.gc() calls |
|*x* |*y*  | *For ..* |

Please add comments into this issue and I'll keep this top table up to date.

**Comment by DanHeidinga** [comment]
| `-Xgcthreads` | `XX:ParallelGCThreads=<N>` | Configure number of GC threads |
| `-Xnuma` | `-XX:+-UseNUMA` | appear similar - investigation needed |

**Comment by DanHeidinga** [comment]
@SueChaplain I had the hotspot & openj9 columns reversed in my two examples.

**Comment by DanHeidinga** [comment]
Also note: https://github.com/eclipse/openj9/issues/2332

**Comment by pdbain-ibm** [comment]
FYI @SueChaplain error (`macine`) in https://www.ibm.com/support/knowledgecenter/en/SSYKE2_8.0.0/com.ibm.java.vm.80.doc/docs/dump_agents_syntax.html
`Add and remove dump agents for various Java™ virtual macine (VM) events.`.
What's the current process for reporting these errors?

**Comment by SueChaplain** [comment]
Consider it fixed @pdbain-ibm :-) For future, errors in the IBM docs need to be raised as issues in the draft KC.

**Comment by SueChaplain** [comment]
These further options identified for garbage collection. Maybe these can go into the next PR to update this topic:

optthruput = `-XX:+UseParallelGC`

optavgpause = Not sure there is an exact equivalent, but you can set `-XX:MaxGCPauseMillis=XXX` to set a target pause time.

gencon = `-XX:+UseConcMarkSweepGC`

balanced = `-XX:+UseG1GC`

**Comment by SueChaplain** [comment]
Another for 0.10.0, which is a Hotspot option that OpenJ9 accepts:

-XX:ActiveProcessorCount=<value>
