### ISSUE TITLE
Remove `-Xifa` as it doesn't apply to OpenJ9

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9-docs#562]
**Page containing the error:**

https://www.eclipse.org/openj9/docs/xifa/

**Describe the error and the update needed:**

Remove this option as OpenJ9 doesn't currently support zOS.

fyi @pshipton

**Comment by SueChaplain** [comment]
@DanHeidinga - we have had [this statement](https://www.eclipse.org/openj9/docs/#supported-environments) in the docs since GA. There is z/OS information throughout. Including it here allows downstream projects that do support z/OS to reuse the documentation. Am I misunderstanding something please?

**Comment by DanHeidinga** [comment]
Thanks Sue for pointing out that statement.  I didn't realize(?)  rememeber(?) that statement had been made.

I had been looking through the docs last night for another option and was surprised to find a clear-zOS specific option in the docs as it's a platform supported internally by IBM.

There's something in this that doesn't sit well with me so I need to think about it some more.

Would also appreciate @pshipton or @mstoodle to weigh in as well.

**Comment by pshipton** [comment]
It would make sense to remove this particular option from OpenJ9 documentation. Although most of the zOS support is part of OpenJ9, this particular option is not.

**Comment by mstoodle** [comment]
I think Peter has provided a valuable way to approach this question more generally, which I think goes to the "doesn't sit well with me" comment Dan made.

If the implementation is in OpenJ9, then anyone could come across it and wonder what it is supposed to do. It's not unreasonable to expect such options are documented. We have allowed a lot of detail about some of these options to be included in our documentation, but that level of detail may also help OpenJ9 developers to better understand how to deal with them in the code.

For the `-Xifa` option, which is not implemented in OpenJ9, I would agree with Dan and Peter that it shouldn't really be documented here. For the other options, I think it's reasonable to document them if they're going to be in the code.

**Comment by DanHeidinga** [comment]
Thanks Mark & Peter for commenting.  I agree with the proposal to remove this option as it's not in the openj9 code while leaving the references to others that are.
