### ISSUE TITLE
Note change to NoClassDefFoundError message class name order

### ISSUE THREAD

**Issue by sharon-wang** [eclipse/openj9-docs#563]
**Issue or pull request number:**
https://github.com/eclipse/openj9/pull/9588

**Overview:**
The order of the class names printed in a NoClassDefFoundError was swapped to match the order Hotspot is using. This swap helps avoid confusion with the previously opposite class name order.

This change should be noted in "What's New".

**Release target:**
Eclipse OpenJ9 0.21.0

**Applies to the following JDK versions:**
All versions.

**Applies to the following platforms:**
All platforms.

**Comment by sharon-wang** [comment]
@pmhayward I'm looking to note this change in the "What's New" page for 0.21.

Currently, there is no `version0.21.md` yet. Is there a template I should use to create this? Or perhaps I would base it off of this commit: https://github.com/eclipse/openj9-docs/commit/bd84040a7a9546924950ce1897cd47e2db197fb6, since 0.21.0 supports also supports OpenJDK 8, 11, and 14.

**Comment by pmhayward** [comment]
@sharon-wang `version0.21.md` has now been created and the PR (#565) merged, so the "What's New" topic for 0.21 is now available for you to add a note when you're ready. Thanks

**Comment by sharon-wang** [comment]
Thank you @pmhayward!
