### ISSUE TITLE
-Xaot should not mention shared classes disabled by default

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9-docs#569]
**Page containing the error:**

https://www.eclipse.org/openj9/docs/xaot/

**Describe the error and the update needed:**

The page mentions that shared classes is not enabled by default, however it is.

**Comment by doveye** [comment]
I made a further update for future-proofing. I removed the sentence about the default behaviour of shared classes altogether, as there's already a link to the "Class data sharing" topic, which describes that. Instead, I expanded on the info the user can get from that topic. This way, the user is still aware that shared classes needs to be enabled for AOT to apply and they can still easily get the shared classes info, but the -Xaot topic won't need to be updated (possibly getting missed again and providing incorrect info) when/if the default shared classes behaviour changes in the future.
