### ISSUE TITLE
Document -XX:[+/-]PrintFlagsFinal

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9-docs#571]
**Issue or pull request number:**
https://github.com/eclipse/openj9/pull/9567
https://github.com/eclipse/openj9/pull/9725

**Overview:**
OpenJ9 adds minimal support for -XX:+PrintFlagsFinal

**Release target:**
Eclipse OpenJ9 0.21.0

**Applies to the following JDK versions:**
all

**Applies to the following platforms:**
all

**For new command line options:**
-XX:[+/-]PrintFlagsFinal

**Comment by pshipton** [comment]
@mstoodle fyi, pls create the PR to update the documentation for the new option.

**Comment by SueChaplain** [comment]
It looks like this change is to help OpenJ9 match the reference implementation, in which case we also need to update the https://eclipse.github.io/openj9-docs/cmdline_migration/ topic. @mstoodle, please confirm and I will add it.

In general, more information in the issue as to why something is changing will help the docs team provide better guidance about where to update the docs. We don't expect developers to know the content to the same extent that we do and we're happy to help ensure complete info. We're also happy to help complete those changes where we can.
