### ISSUE TITLE
Update information regarding build environments

### ISSUE THREAD

**Issue by keithc-ca** [eclipse/openj9-docs#581]
**Pull request:**
*https://github.com/eclipse/openj9/pull/9933*

**Overview:**
*Minimum build requirements have changed, making https://eclipse.github.io/openj9-docs/openj9_support/#build-environments out-of-date.*

**Release target:**
*Eclipse OpenJ9 0.21.0*

**Applies to the following JDK versions:**
*All*

**Applies to the following platforms:**
*At least macOS.*

**Comment by pshipton** [comment]
I don't expect the documentation should change until OpenJ9 actually changes how OSX is building https://github.com/eclipse/openj9/issues/9806.

**Comment by SueChaplain** [comment]
@keithc-ca is it likely that the Adopt change will happen in time for the 0.21.0 release or should we bump this to 0.22.0 please?

**Comment by keithc-ca** [comment]
I'm not clear what changes, if any, are required at Adopt: I think they're already using the OS and Xcode versions mentioned in eclipse/openj9#9933.

**Comment by SueChaplain** [comment]
@pshipton @keithc-ca - we plan to publish 0.21.0 today. Presumably this work is bumped to 0.22.0? Please confirm so that I can move the milestone.

**Comment by pshipton** [comment]
Although we've updated the build instructions for Mac to suggest newer versions of the tooling, the OpenJ9 project hasn't yet made any change to how Mac builds are created, https://github.com/eclipse/openj9/issues/9806. Therefore the older build environment is still supported. I feel this change can wait until the OpenJ9 builds are modified.
