### ISSUE TITLE
verbose:module/nomodule support

### ISSUE THREAD

**Issue by theresa-m** [eclipse/openj9-docs#593]
**Issue or pull request number:**
https://github.com/eclipse/openj9/issues/9248
https://github.com/eclipse/openj9/pull/10095

**Overview:**
-verbose:module and -verbose:nomodule support for OpenJ9. I will create an update for `docs/cmdline_general.md` and release notes.

**Release target:**
0.25.0

**Applies to the following JDK versions:**
9 and later

**Applies to the following platforms:**
All platforms

**Comment by pmhayward** [comment]
@theresa-m ... Hi Theresa, Is this in plan for 0.22.0? If so, I'll update the milestone. Thanks!

**Comment by theresa-m** [comment]
This will not be part of 0.22.

**Comment by pmhayward** [comment]
Thanks - will move it to our backlog

**Comment by pshipton** [comment]
The option is documented on this page https://eclipse.github.io/openj9-docs/cmdline_general/

**Comment by theresa-m** [comment]
Would this need release notes for both 0.25 (16) and 0.26 (8,11) ?

**Comment by pshipton** [comment]
I think just 0.25, and the docs team will take care of it after that. We can create a PR, but it can't be merged until the 0.24 split has occurred.
