### ISSUE TITLE
Document -XX:ActiveProcessorCount= flag, for specifying number of CPUs

### ISSUE THREAD

**Issue by Ali-Ni** [eclipse/openj9-docs#60]
**Issue or pull request number:**
https://github.com/eclipse/openj9/pull/2196

**Overview:**
This command redefines the number of CPUs the VM considers when creating threads, overriding automatic number of CPU detection. This adds some functionality for the user to tune the degree to which the VM parallelizes with a command line flag.

This change also affects the javacore. In `JavaCoreDumpWriter::writeCPUinfo`, if `J9PORT_CPU_TARGET` is not equal to `J9PORT_CPU_BOUND`, it indicates that Target CPUs is being overridden by Active CPUs. A new line is added - "2CIACTIVECPU Active CPUs: " - which is equal to Target CPUs if it is being overridden, and zero otherwise. 

**Applies to the following JDK versions:**
8 and later

**Applies to the following platforms:**
All platforms

**For new command line options:**

- Option name and syntax: `-XX:ActiveProcessorCount=<value>`
- If values are set:  
	- Units for setting: Number of processors 
	- Range: 1+
	- Default value: None
- Purpose: Set a value to override all number of CPU detection, and consider this value when deciding the number of threads to create for the VM's various operations
- Restrictions:

**Comment by SueChaplain** [comment]
Docs updated, closing issue
