### ISSUE TITLE
MemoryMXBean method rename

### ISSUE THREAD

**Issue by theresa-m** [eclipse/openj9-docs#607]
**Issue or pull request number:**
https://github.com/eclipse/openj9/pull/10217

**Overview:**
getGCSlaveThreadsCpuUsed and getGCMasterThreadCpuUsed have been deprecated for removal in Java15, and will be removed in Java 16.
New methods getGCMainThreadCpuUsed and getGCWorkerThreadsCpuUsed should be used instead

**Release target:**
0.22

**Applies to the following JDK versions:**
8 and later

**Applies to the following platforms:**
All platforms

See docs:
https://www.eclipse.org/openj9/docs/api-langmgmt/
https://www.eclipse.org/openj9/docs/api/jdk8/jre/management/extension/com/ibm/lang/management/MemoryMXBean.html

- [x] release notes
- [x] jdk8 api changes (index, deprecated list, MemoryMXBean page)
- [x] jdk 11 api changes (index, deprecated list, MemoryMXBean page)

**Comment by pmhayward** [comment]
@theresa-m ... Hi Theresa, Just keeping tabs on outstanding 0.22.0 doc issues. Is this one still in plan for this release? FYI, we're aiming to get all docs finished by milestone 2 (31 Aug), in part due to vacations in our team. Thanks!

**Comment by theresa-m** [comment]
Yes this is still for 0.22. I should have a pull request ready in the next day or two.

**Comment by theresa-m** [comment]
The fix for this issue is: https://github.com/eclipse/openj9-docs/pull/618
