### ISSUE TITLE
Document -XX:[+|-]PortableSharedCache

### ISSUE THREAD

**Issue by harryyu1994** [eclipse/openj9-docs#615]
**Issue or pull request number:**
https://github.com/eclipse/openj9/pull/9731
https://github.com/eclipse/openj9/pull/9993
https://github.com/eclipse/omr/pull/5436
https://github.com/eclipse/openj9/pull/10305

**Overview:**
This option enables AOT compiled code to be generated based on a chosen set of processor features (features present in the Intel Sandy Bridge microarchitecture) that maximizes its portability across machines. It is currently supported only on x86. The feature is turned on by default in Docker containers and can be disabled with `-XX:-PortableSharedCache`. To enable the portable shared cache feature outside Docker containers, `-XX:+PortableSharedCache` needs to be specified for the initial Java Virtual Machine instance (when the creation of the Shared Class Cache happens) as well as for every subsequent instance that make use of the same Shared Class Cache. 

This option is especially useful for Java applications deployed on the cloud in the form of Docker containers as it allows the Shared Class Cache to be portable across processors with different CPU microarchitectures and across Java Virtual Machines with different heap sizes.

**Release target:**
Eclipse OpenJ9 0.22.0

**Applies to the following JDK versions:**
all

**Applies to the following platforms:**
x86

**For new command line options:**
-XX:[+|-]PortableSharedCache

**Comment by pmhayward** [comment]
Resolved by #582
