### ISSUE TITLE
Update documentation for -XX:[+|-]PortableSharedCache

### ISSUE THREAD

**Issue by harryyu1994** [eclipse/openj9-docs#630]
**Issue or pull request number:**
https://github.com/eclipse/openj9-docs/pull/631
https://github.com/eclipse/openj9-omr/pull/74
https://github.com/eclipse/openj9/pull/10549

**Overview:**
Introduced additional changes to the Portable Shared Cache feature (`-XX:[+|-]PortableSharedCache`) which eliminates the AOT portability issues of Compressed Reference OpenJ9 builds with heap sizes from 0GB to 28GB. Previously compressed reference JVMs with different heap sizes cannot share AOT compiled code with each other. When Portable Shared Cache is enabled (either via `-XX:[+|-]PortableSharedCache` or by default in containers), Compressed Reference OpenJ9 builds with heap size in the range of 0GB to 28GB will be able to share AOT complied code with each other. However there will be a slight steady-state throughput penalty of 1-2% when using this option now compared to before.

**Release target:**
Eclipse OpenJ9 0.23.0

**Applies to the following JDK versions:**
8 and later

**Applies to the following platforms:**
Linux X / Windows

**For new command line options:**
N/A, same command line option as before (`-XX:[+|-]PortableSharedCache`)

**Comment by harryyu1994** [comment]
Closing this issue as it has been addressed by #631

**Comment by SueChaplain** [comment]
@harryyu1994 - for the release notes, please can you confirm the OpenJ9 issue/PR that made the changes please? The ones referenced here were closed without merging and nothing is mentioned in #631. Thanks

**Comment by harryyu1994** [comment]
> @harryyu1994 - for the release notes, please can you confirm the OpenJ9 issue/PR that made the changes please? The ones referenced here were closed without merging and nothing is mentioned in #631. Thanks

I updated the references from:
https://github.com/eclipse/openj9-omr/pull/74
https://github.com/eclipse/openj9/pull/10549
to
https://github.com/eclipse/omr/pull/5436
https://github.com/eclipse/openj9/pull/10305

Those PRs were closed because they didn't make it into release 0.22.
I confirmed that they are in release 0.23.

**Comment by SueChaplain** [comment]
Sorry @harryyu1994 - just to confirm, as I've not been around for the history on this one. Is what we have in the 0.23 topic accurate? https://eclipse.github.io/openj9-docs/version0.23/#-xx-portablesharedcache-option-behavior-update .. if so, it's the issue number for this change that I need. If that's 10305 fine, but I got confused with the commit update on the open PR?

**Comment by harryyu1994** [comment]
> Sorry @harryyu1994 - just to confirm, as I've not been around for the history on this one. Is what we have in the 0.23 topic accurate? https://eclipse.github.io/openj9-docs/version0.23/#-xx-portablesharedcache-option-behavior-update .. if so, it's the issue number for this change that I need. If that's 10305 fine, but I got confused with the commit update on the open PR?

Yes 0.23 topic is accurate, and 10305 is the change.

Which open PR? https://github.com/eclipse/openj9-docs/pull/637? The changes described in this one have not been merged yet and should be targeting 0.24. I guess I will open another issue for that PR.
