### ISSUE TITLE
-XX:HeapDumpPath an alias for -Xdump:directory

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/openj9-docs#65]
**Issue or pull request number:**
https://github.com/eclipse/openj9/pull/2508

**Overview:**
This adds the OpenJDK option `-XX:HeapDumpPath` as a synonym for `-Xdump:directory`

**Applies to the following JDK versions:**
8 and later
**Applies to the following platforms:**
All platforms
**For new command line options:**

- Option name and syntax: *-XX:HeapDumpPath=<directory>*
- Purpose: This sets the directory for all JVM dumps including heap dumps, javacores, system dumps, etc.  This option is added for compatibility with OpenJDK.
- Restrictions: None.

**Comment by pmhayward** [comment]
@pdbain-ibm , @pshipton  Quick query: this "alias" option says it's for all platforms, whereas the -Xdump option in the current docs (https://www.eclipse.org/openj9/docs/xdump/#syntax) says -Xdump:directory is Linux only. Is one of those statements therefore incorrect?

**Comment by pshipton** [comment]
It appears (https://www.eclipse.org/openj9/docs/xdump/#syntax) is incorrect, I don't see the Linux restriction reflected in the IBM docs.

**Comment by pdbain-ibm** [comment]
@DanHeidinga I see no Linux-specific code in dmpsup.c.  I expect the latter statement is wrong.

**Comment by pmhayward** [comment]
@pdbain-ibm @pshipton Thanks both - I'll remove the restriction from the -Xdump topic.
