### ISSUE TITLE
Parse -Xlog:gc variants for compatibility

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9-docs#671]
**Issue or pull request number:**
https://github.com/eclipse/openj9/pull/11082

**Overview:**
See also https://github.com/eclipse/openj9-docs/issues/658
When `-XX:-LegacyXlogOption` is in effect, which is the default for OpenJ9 builds (but not IBM), parse the `-Xlog:gc` variants for compatibility with Hotspot, and enable `-verbose:gc` or `-Xverbosegclog:`.

**Release target:**
Eclipse OpenJ9 0.24.0

**Applies to the following JDK versions:**
All

**Applies to the following platforms:**
All

**For new command line options:**

`-Xlog` options such as the following enable `-verbose:gc`, or `-Xverbosegclog:` when a file is set
`-Xlog:gc` - enables `-verbose:gc`
`-Xlog:gc:stderr` - enables `-verbose:gc`
`-Xlog:gc:<file>` - enables `-Xverbosegclog:<file>`
`-Xlog:gc:file=<file>` - enables `-Xverbosegclog:<file>`
`%p` and `%t` are supported in the file name for compatibility. These are mapped to standard OpenJ9 tokens. `%p` maps to `%pid` and `%t` to `%Y-%m-%d_%H-%M-%S`.

When other forms of `-Xlog` are specified that are intended to enable more than just verbose gc, print a warning that the option is not recognized (`JVMJ9VM007W Command-line option unrecognised:`), but also enable verbose gc logging. Examples:
`-Xlog`
`-Xlog:all`
`-Xlog:something+gc` or `-Xlog:gc+something` 
`-Xlog:something,gc` or `-Xlog:gc,something` 
`-Xlog:gc:stdout`

**Comment by SueChaplain** [comment]
Additional work completed in #681. Closing.
