### ISSUE TITLE
Concurrent Scavenge GC Page Broken Links

### ISSUE THREAD

**Issue by bragaigor** [eclipse/openj9-docs#677]
**Page containing the error:**

*https://www.eclipse.org/openj9/docs/gc/#concurrent-scavenge*

**Describe the error and the update needed:**

Both links under Concurrent Scavenge are stale. Maybe they were moved somewhere else?
```
 -  Reducing Garbage Collection pause times with Concurrent Scavenge and the Guarded Storage Facility
 -  How Concurrent Scavenge using the Guarded Storage Facility Works
```

Maybe we can have one link pointing to this blog post: https://blog.openj9.org/2019/03/25/concurrent-scavenge-garbage-collection-policy/

**Comment by bragaigor** [comment]
cc @amicic @dmitripivkine

**Comment by SueChaplain** [comment]
The dev center has moved onto IBM Support, but the blog posts that were there are waiting to be checked and put onto IBM developer by the developer content team (@davehobbs - unsure or progress?). We'll get them onto the OpenJ9 blog if they don't already exist there and update the links. 

Thanks for picking this up @bragaigor - I'll do a general sweep and make sure there was nothing else that dropped in the same way.
