### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by LinuxSuRen** [eclipse/openj9-docs#69]
**Subject:**
Let more people focus and learn from openj9.

**Suggestion:**
Add multi-language support will be very helpful. Does anyone know how to do that?

**Comment by doveye** [comment]
Unfortunately, MkDocs does not currently support multiple-languages, and it doesn't look like it will any time soon either - see https://github.com/mkdocs/mkdocs/issues/617.

**Comment by LinuxSuRen** [comment]
Thanks for your response.
