### ISSUE TITLE
Java 8 builds with VS2013

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9-docs#691]
**Issue or pull request number:**
https://github.com/eclipse/openj9/issues/10129

**Overview:**
VS2010 is out of support. OpenJ9 builds Java 8 with VS2013 on Windows.

**Release target:**
0.24.0

**Applies to the following JDK versions:**
8 only

**Applies to the following platforms:**
Windows

**Comment by pshipton** [comment]
Dup of #662

**Comment by SueChaplain** [comment]
Closed by #663
