### ISSUE TITLE
Add new option for -Xcheck:jni

### ISSUE THREAD

**Issue by SueChaplain** [eclipse/openj9-docs#693]
**Pull request number:**
https://github.com/eclipse/openj9/pull/11000

**Overview:**
Add new abortonerror option to cause JNI check to run the RAS abort
handler when a fatal JNI error occurs. The diagnostics created are
controlled by the -Xdump:abort configuration.

**Release target:**
Eclipse OpenJ9 0.24.0

**Applies to the following JDK versions:**
All versions

**Applies to the following platforms:**
All platforms

**For new command line options:**

- Option name -Xcheck:jni suboption

- Purpose: Diagnostics for fatal JNI errors

**Comment by SueChaplain** [comment]
@pshipton or @gacholio 

Ref https://github.com/eclipse/openj9/pull/11000, I misunderstood Peter's comment about adding a release note. We should add this to the docs as well as the OpenJ9 release notes for 0.24.

I'll write a very short entry for the what's new but I'll need one or other of you to review.

**Comment by pshipton** [comment]
Sure.
