### ISSUE TITLE
Confusing default between -XX:[+|-]DisableExplicitGC and ‑Xenableexplicitgc / ‑Xdisableexplicitgc

### ISSUE THREAD

**Issue by mbarbero** [eclipse/openj9-docs#718]
**Page containing the error:**

https://www.eclipse.org/openj9/docs/xxdisableexplicitgc/
https://www.eclipse.org/openj9/docs/xenableexplicitgc/

**Describe the error and the update needed:**

In the hotspot's option page, it says that the default is `-XX:+DisableExplicitGC` (explicit GC is disabled) while in the Openj9's option page, it says that the default is `-Xenableexplicitgc` (explicit GC is enabled). Which one is correct? 

Both options are aliases (as per https://www.eclipse.org/openj9/docs/cmdline_migration/), so I'm expecting that the default value to be the same for both.

Finally, on both pages, the effect description says:
* _Enable GC_ 
* _Disable GC_

I think it would be more accurate to say 
* _Disable explicit GC calls (i.e., calls to `System.gc()`)_ 
* _Disable explicit GC calls (i.e., calls to `System.gc()`)_.

**Comment by dmitripivkine** [comment]
Just FYI how it works actually:

- `-XX:+DisableExplicitGC` is mapped to `-Xdisableexplicitgc`
- `-XX:-DisableExplicitGC` is mapped to `-Xenableexplicitgc`
- default for OpenJ9 for all GC policies is `-Xenableexplicitgc` with exception for `-Xgcpolicy:nogc` where default is `-Xdisableexplicitgc`

**Comment by SueChaplain** [comment]
@mbarbero - thank you for raising the issue, and thank you @dmitripivkine for providing some clarification. We'll get this addressed as soon as possible.

**Comment by mbarbero** [comment]
Thanks @SueChaplain @dmitripivkine !
