### ISSUE TITLE
Doc updates to support OpenJ9 0.10.0 release (Sept)

### ISSUE THREAD

**Issue by SueChaplain** [eclipse/openj9-docs#72]
**What's new:**
*Add new features and significant changes since 0.9.0*

**Supported environments:**
*Update the topic to include supported platforms and build environment for OpenJDK11*

**Comment by SueChaplain** [comment]
@pshipton 

I need to create an OpenJDK 11 table like this one, and remove the tables from 9 & 10. Please can you confirm if the supported platforms are identical to 10: https://www.eclipse.org/openj9/docs/openj9_support/#openjdk-10

I also need to create an OpenJDK 11 table for the build environment: https://www.eclipse.org/openj9/docs/openj9_support/#openjdk-10_1
Please can you confirm system/compiler levels or point me to an issue where I can find this?

**Comment by pshipton** [comment]
@SueChaplain you can duplicate the supported platform table from Java 10, nothing is changed for Java 11. The linux compilers will move shortly to gcc 7.3 for Java 11 (https://github.com/eclipse/openj9/pull/2718), and Windows will move to MSVC 2017. While it would be nice if this occurred for the 0.10.0 release I can't guarantee it so you may want to wait and make the changes when they actually occur.

**Comment by SueChaplain** [comment]
@pshipton @DanHeidinga @mstoodle Are you ok for me to remove the JDK 9 and JDK 10 columns from the support table, and remove the sections for OpenJDK9 and OpenJDK10 that cover platform support and build environments please? See: https://www.eclipse.org/openj9/docs/openj9_support/

**Comment by pshipton** [comment]
+1

**Comment by DanHeidinga** [comment]
+1 to removing JDK9 column.
I'd like to keep the JDK10 column until  the 0.11.0 (Oct) release goes out.  That will likely be the last time we build JDK10.
