### ISSUE TITLE
Document zlib library changes on AIX systems

### ISSUE THREAD

**Issue by rmnattas** [eclipse/openj9-docs#722]
**Issue or pull request number:**
https://github.com/eclipse/openj9/issues/11624

**Overview:**
This change set OpenJ9 to use the hardware accelerated compression library `zlibNX` by default on AIX systems that has an NX accelerator (POWER9 and newer) enabled.

These changes set system zlib as default instead of bundled zlib for jdk8, jdk16 and jdk(next) (jdk11 has system zlib already as default). It prepends `zlibNX` into `LIBPATH` on eligible AIX systems to get the best compression performance when available.
The `zlibNX` library will be installed by default on AIX 7.3, and can be installed on AIX 7.2 TL4 and later.

**Release target:**
Eclipse OpenJ9 0.25.0

**Applies to the following JDK versions:**
8 and later

**Applies to the following platforms:**
AIX

**Comment by pshipton** [comment]
Can AIX 7.1 install the library? OpenJ9 support is for AIX 7.1 TL5+ and AIX 7.2 TL3+.

**Comment by rmnattas** [comment]
> Can AIX 7.1 install the library? OpenJ9 support is for AIX 7.1 TL5+ and AIX 7.2 TL3+.

It cannot be installed in AIX 7.1

It can be installed starting with AIX 7.2 TL4
It will also be installed by default on AIX 7.3

**Comment by SueChaplain** [comment]
**Notes:**

- Add a new section to "Getting started" under "Performance tuning" for "Hardware acceleration".
- Usual updates for release topic.

**Comment by SueChaplain** [comment]
@rmnattas Hi - are you planning on creating a PR for documentation changes (standard practice) or are you wanting some help from the doc team please? 

Also, presume this a suitable place to direct users for optimizing / helping with use of `zlibnx` on AIX?
https://www.ibm.com/support/knowledgecenter/ssw_aix_72/performance/zlibNX.html

**Comment by rmnattas** [comment]
Hi @SueChaplain, I'll work on a PR. I may require some help and will reach out in that case.


> Also, presume this a suitable place to direct users for optimizing / helping with use of `zlibnx` on AIX?
> https://www.ibm.com/support/knowledgecenter/ssw_aix_72/performance/zlibNX.html

Yes, I believe thats the best documentations for it.
