### ISSUE TITLE
List features in OpenJDK 16 that apply to OpenJ9

### ISSUE THREAD

**Issue by SueChaplain** [eclipse/openj9-docs#726]
**Subject:**
http://openjdk.java.net/projects/jdk/16/ lists the features targeted for this release.

**Suggestion:**
List the ones that would apply to an OpenJDK that is built with OpenJ9 in the release topic. Call out important change https://openjdk.java.net/jeps/396, which might affect users apps.

**Comment by pshipton** [comment]
The following jdk16 JEPs apply to OpenJ9.

338: Vector API (Incubator) - the OpenJDK impl works as-is, but OpenJ9 is adding optimization. TBD what makes it into 0.25

390: Warnings for Value-Based Classes
395: Records
397: Sealed Classes (Second Preview)

The following apply to OpenJ9 but are deferred to a future OpenJ9 release.

389: Foreign Linker API (Incubator)
393: Foreign-Memory Access API (Third Incubator)

The following don't apply directly to OpenJ9 but are part of OpenJDK so included in OpenJ9 builds.

347: Enable C++14 Language Features
380: Unix-Domain Socket Channels
394: Pattern Matching for instanceof
396: Strongly Encapsulate JDK Internals by Default

392: Packaging Tool - see https://github.com/eclipse/openj9/issues/11028 and https://github.com/eclipse/openj9-docs/issues/664

The following don't apply.

357: Migrate from Mercurial to Git
369: Migrate to GitHub
376: ZGC: Concurrent Thread-Stack Processing
386: Alpine Linux Port
387: Elastic Metaspace
388: Windows/AArch64 Port

**Comment by pshipton** [comment]
@tajila fyi

**Comment by tajila** [comment]
https://github.com/eclipse/openj9-docs/issues/726#issuecomment-770847916 looks good
