### ISSUE TITLE
Document class unloading options

### ISSUE THREAD

**Issue by amicic** [eclipse/openj9-docs#756]
-Xgc:classUnloadingThreshold=
-Xgc:classUnloadingKickoffThreshold=

The former is a threshold used to trigger an optional GC operation of class unloading in Global GC, irrespective of how Global GC itself is triggered. The option is applicable to Gencon, Optavgpause and Optthurput
Default threshold is 6.

The latter is a threshold used to trigger/kickoff an early Concurrent Global GC cycle start based on recent class _loading_ activity, which otherwise typically would be triggered at a later point due to low heap free memory. Applicable to Gencon and Optavgpause.
Default threshold is 80000.

For both options the value that is compared with the threshold is:
number of class loaders (not classes!) + number of anonymous classes  loaded since the previous class unloading operation.

**Comment by amicic** [comment]
cc: @dmitripivkine

**Comment by SueChaplain** [comment]
@amicic and @dmitripivkine - are these new options for 0.26.0 or a previously undocumented ones please?

**Comment by amicic** [comment]
They've existed for many years, now,
