### ISSUE TITLE
Update documentation for jextract

### ISSUE THREAD

**Issue by keithc-ca** [eclipse/openj9-docs#767]
**Overview:**
*The `jextract` command is deprecated; the replacement is `jpackcore`.*

**Release target:**
*Eclipse OpenJ9 0.26.0*

See eclipse/openj9#11278.

**Comment by SueChaplain** [comment]
@keithc-ca, based on your comment I some questions:

>The plan is that jpackcore will be equivalent to (i.e. an alias for) jextract in all versions of Java where openjdk does not provide a different tool named jextract. Then you will be able to use jpackcore in any (recent) build independent of whether jextract means the same thing.

- we announce as deprecated in 0.26.0, to be removed in a future release, but do not mention jpackcore
- we document jpackcore for all releases when?
- in 0.28.0, we mark jextract original as 8 & 11 only in the docs and leave it there until when? EOS on OpenJDK 11?
- in 0.28.0, we introduce a new jextract for 17+ for Panama

**Comment by keithc-ca** [comment]
We can announce `jpackcore` in 0.26 for all releases.
When the Panama variant of `jextract` is released (17?) it will replace the openj9 tool that had that name.
I see no value in removing `jextract` from 8 or 11.
To be clear, 'we' are not introducing the new `jextract`, it will come from openjdk upstream.
