### ISSUE TITLE
Keep Breadth First to be default Scan Ordering for Balanced in 0.26.0

### ISSUE THREAD

**Issue by dmitripivkine** [eclipse/openj9-docs#768]
**Issue or pull request number:**
*https://github.com/eclipse/openj9/pull/12369 for head*
*https://github.com/eclipse/openj9/pull/12406 for 0.26.0 release*

**Overview:**
*Scan Ordering default planned to be changed from Breadth First to Dynamic Breadth First for Balanced is reverted due problem.  Breadth First still be default Scan Ordering for Balanced*

**Release target:**
*Eclipse OpenJ9 0.26.0*

**Applies to the following JDK versions:**
*8 and later*

**Applies to the following platforms:**
*All platforms*

**Comment by dmitripivkine** [comment]
I am sorry but we need to revert to have Breadth First default Scan Ordering for Balanced due late problem discovery. This is temporary and I hope we will be able to change default to Dynamic Breadth first in the next release.
I found these documents should be updated so far:

https://eclipse.github.io/openj9-docs/version0.26/
https://eclipse.github.io/openj9-docs/gc_overview/#gc-copy-forward-operation
https://eclipse.github.io/openj9-docs/xgc/#dynamicbreadthfirstscanordering
https://github.com/eclipse/openj9/blob/master/doc/release-notes/0.26/0.26.md

**Comment by dmitripivkine** [comment]
@ jonoommen Would you please work on this?

**Comment by SueChaplain** [comment]
Hi @jonoommen ... I didn't spot Dmitri's request for you to work on this. I've raised a PR - please can you review?
