### ISSUE TITLE
Add further options to migration topic (cmdline_migration.md)

### ISSUE THREAD

**Issue by pmhayward** [eclipse/openj9-docs#77]
Further options noted in #55 after PR by @SueChaplain (5 Sep 2018) have moved to this new issue:

Options identified for garbage collection. 
optthruput = -XX:+UseParallelGC
optavgpause = Not sure there is an exact equivalent, but you can set -XX:MaxGCPauseMillis=XXX to set a target pause time.
gencon = -XX:+UseConcMarkSweepGC
balanced = -XX:+UseG1GC

Another for 0.10.0, which is a Hotspot option that OpenJ9 accepts:
-XX:ActiveProcessorCount=<value>

**Comment by SueChaplain** [comment]
As new options are added, these are raised as new docs issues. Closing this older item, which details options that are already in the published docs.
