### ISSUE TITLE
Change to default shared cache size on OpenJ9 Java 8.

### ISSUE THREAD

**Issue by hangshao0** [eclipse/openj9-docs#80]
In v0.9.0 we changed the default shared cache size on Java 9 and up on 64-bit platforms. The doc change request was https://github.com/eclipse/openj9-docs/issues/46. 
We are now backporting the same change onto OpenJ9 Java 8 on 64-bit platforms (Targeted at 0.11.0). 

**Issue or pull request number:**
*https://github.com/eclipse/openj9/issues/1938, https://github.com/eclipse/openj9/pull/2784*

**Overview:**
The default shared cache size will be used if user does not specify "-Xscmx" or "-XX:SharedCacheHardLimit=" in the command line when creating a new shared cache. The default shared cache size is changed to 300MB with a softmax size of 64MB on 64-bit platforms on OpenJ9 Java 8, with the following 2 exceptions:

    For persistent cache, if the free disk space is < 6GB, we will set the default cache size to 64MB with no softmax size.
    For non-persistent cache, the cache size is limited by SHMMAX. If SHMMAX < 300MB, the default shared cache size will be set to SHMMAX. There will be a softmx setting of 64MB if the default cache size (which is SHMMAX in this case) > 80MB. Otherwise, we won't set softmx.
.

**Applies to the following JDK versions:**
OpenJ9 Java 8 only

**Applies to the following platforms:**
All 64-bit platforms

**For new command line options:**
N.A.

**Comment by doveye** [comment]
Docs updated
