### ISSUE TITLE
jpackcore doesn't list all supported operating systems

### ISSUE THREAD

**Issue by kgibm** [eclipse/openj9-docs#853]
**Page containing the error:**

https://www.eclipse.org/openj9/docs/tool_jextract/

**Describe the error and the update needed:**

The page writes:

> (AIX®, Linux®, macOS®)

However, `jpackcore` is available on other operating systems. For example, on Windows, there is `jpackcore.exe`.

**Comment by pshipton** [comment]
`jpackcore` is available on other OSes, and will work, but only needs to be used on the OSes listed (AIX, Linux, macOS). Windows includes the relevant content in the system core file so we don't need users to run `jpackcore` to collect it.
