### ISSUE TITLE
Add repo to Hacktoberfest

### ISSUE THREAD

**Issue by AdamBrousseau** [eclipse/openj9-docs#861]
**Subject:**
Community Engagement

**Suggestion:**
We already have the hacktoberfest label on OpenJ9 and OMR. I don't think it would hurt to add the label/tag to the Docs repo, and all other openj9 repos for that matter. This could encourage outside collaborators.

When users land PRs in participating project repos, they get a contribution towards their hacktoberfest profile.
https://hacktoberfest.digitalocean.com/

**Comment by pshipton** [comment]
Done
