### ISSUE TITLE
-Xcomp unneeded in https://www.eclipse.org/openj9/docs/cmdline_migration/

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9-docs#87]
I'm not sure why the -Xcomp line is needed in https://www.eclipse.org/openj9/docs/cmdline_migration/

OpenJ9 already understands -Xcomp and maps it to -Xjit:count=0 so the user doesn't need to do this.

https://github.com/eclipse/openj9/blob/4833764455a3a3a9c0873ffb2e353d8b121ba49e/runtime/vm/jvminit.c#L3730

**Comment by SueChaplain** [comment]
Sounds like it needs moving to the top table. As this topic evolves I think we probably want to change it to document only the options that aren't supported but have similar OpenJ9 ones. Documenting stuff we have aliased isn't that important to a user, which is pretty much the top table!

**Comment by pshipton** [comment]
The current OpenJ9 behavior is to ignore any option that starts with -XX: that are not understood. This can make it confusing for customers to know if the option is accepted or not. It also doesn't help when an option gets misspelled. To address this I've created https://github.com/eclipse/openj9/issues/2977

**Comment by pshipton** [comment]
I see -Xcomp is deprecated in the docs, even though we recently added it for compatibility. Not sure why its deprecated exactly. Since it is deprecated, there should be a note that while it can be used for compatibility, using -Xjit:count=0 is preferred. I also note OpenJDK has a -XX:CompileThreshold option, which I've added to the list in #2332
