### ISSUE TITLE
freetype is required to load libfontmanager.so

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9-docs#908]
**Subject:**
The freetype library (libfreetype.so, libfreetype.a) is required to load libfontmanager.so

**Suggestion:**
Document that libfreetype is a prereq to using libfontmanager.so (awt?, the java.desktop module in Java 11) and the user needs to install this prereq or trying to load libfontmanager.so will result in UnsatifiedLinkError.
` java.lang.UnsatisfiedLinkError: fontmanager (Not found in com.ibm.oti.vm.bootstrap.library.path)`

**Comment by doveye** [comment]
@pshipton can this be closed now? Looks like there is an entry for this in the 0.32 release notes.

**Comment by pshipton** [comment]
There was a note added to https://github.com/eclipse-openj9/openj9/blob/master/doc/release-notes/0.32/0.32.md and as discussed with Esther this is sufficient. We don't need to add the same note to the User Guide.
