### ISSUE TITLE
DDR enabled on AIX

### ISSUE THREAD

**Issue by mikezhang1234567890** [eclipse/openj9-docs#92]
**Issue or pull request number:**
https://github.com/eclipse/openj9/issues/378
https://github.com/eclipse/openj9/issues/1769
PR - https://github.com/eclipse/openj9/pull/3995

**Overview:**
The docs should be changed to indicate that AIX is now a supported platform for DDR.
Users can now use the DDR tool to help debug their AIX Java applications.

**Applies to the following JDK versions:**
8 and later

**Applies to the following platforms:**
AIX

**For new command line options:**
Same as DDR commands for other platforms.

**Comment by SueChaplain** [comment]
@mikezhang1234567890 - I've handled this change in the release notes, where we previously had the lack of DDR support for AIX as an issue. Not that the entry is removed in the limitations table and support added as a notable change in the top table: https://github.com/eclipse/openj9/pull/2766/files

We did not include the lack of DDR support directly in the user docs, so no changes needed in this repo.

**Comment by pshipton** [comment]
@SueChaplain I'm not expecting DDR AIX support to go in for 0.10.0. Its not 100% ready and other problems for 0.10.0 are taking priority.

**Comment by SueChaplain** [comment]
@pshipton Yeah I wish I'd read your 0.11 release plan earlier :-/ I'll back it out on Monday.

**Comment by SueChaplain** [comment]
Target = 0.12.0

**Comment by pshipton** [comment]
The changes are merged.

**Comment by SueChaplain** [comment]
Will remove the restriction from the release notes for 0.12.0.

**Comment by SueChaplain** [comment]
Removed restriction via PR https://github.com/eclipse/openj9/pull/4076 ahead of December milestone build.

**Comment by SueChaplain** [comment]
See https://github.com/eclipse/openj9/blob/master/doc/release-notes/0.12/0.12.md
Closing.
