### ISSUE TITLE
Remove note about restriction on DDR use

### ISSUE THREAD

**Issue by keithc-ca** [eclipse/openj9-docs#97]
https://github.com/eclipse/openj9/pull/7064

**Overview:**
The pull request listed above, once merged, will remove this restriction mentioned in version0.9.md
> You must use a 32-bit JVM to look at a 32-bit core, and a 64-bit JVM to look at a 64-bit core.

**Applies to the following JDK versions:**
All

**Applies to the following platforms:**
All platforms with DDR support

**Comment by SueChaplain** [comment]
@keithc-ca - can you confirm that this is also related to https://github.com/eclipse/openj9/issues/2507

**Comment by pshipton** [comment]
Yes it is. If you look at eclipse/openj9#3099 it shows "Fixes #2507"

**Comment by SueChaplain** [comment]
Target = 0.12.0

**Comment by pshipton** [comment]
Expected delivery is in the 0.17 release.

**Comment by pmhayward** [comment]
Resolved by PR #379
