### ISSUE TITLE
No documentation for jdmpview !j9help command

### ISSUE THREAD

**Issue by tajila** [eclipse/openj9-docs#98]
Add documentation for jdmpview !j9help command

There are over a 100 jdmpview commands and only a small number of those are documented in https://www.eclipse.org/openj9/docs/tool_jdmpview. For those unfamiliar with jdmpview it is very difficult to understand how to use it and what its capabilities are. jdmpview has a command called `!j9help` which displays all the available (alternate) "expert" commands as well as a short description describing what each command does. !j9help is currently not documented so any potential user will be unaware of this. Adding documentation for !j9help will make it easier for first time users to understand jdmpview's capabilities. 

In the long term would ideally have documentation for each of the commands.

A plan to update the documentation is in https://github.com/eclipse/openj9/issues/3100

**Comment by SueChaplain** [comment]
@paulcheeseman Paul, do you think this is another candidate for an option builder?
